// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CrawlTaskCreateSchema = {
    properties: {
        crawl_type: {
            '$ref': '#/components/schemas/DouyinCrawlType',
            default: 'search'
        },
        login_type: {
            '$ref': '#/components/schemas/DouyinLoginType',
            default: 'qrcode'
        },
        browser_mode: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DouyinBrowserMode'
                },
                {
                    type: 'null'
                }
            ]
        },
        cookies: {
            anyOf: [
                {
                    type: 'string',
                    format: 'password',
                    writeOnly: true
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cookies'
        },
        keywords: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 20,
            title: 'Keywords'
        },
        video_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 1000,
            title: 'Video Ids'
        },
        creator_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 100,
            title: 'Creator Ids'
        },
        start_page: {
            type: 'integer',
            minimum: 1,
            title: 'Start Page',
            default: 1
        },
        max_awemes: {
            type: 'integer',
            maximum: 1000,
            minimum: 1,
            title: 'Max Awemes',
            default: 10
        },
        fetch_comments: {
            type: 'boolean',
            title: 'Fetch Comments',
            default: true
        },
        fetch_sub_comments: {
            type: 'boolean',
            title: 'Fetch Sub Comments',
            default: false
        },
        max_comments_per_aweme: {
            type: 'integer',
            maximum: 1000,
            minimum: 1,
            title: 'Max Comments Per Aweme',
            default: 10
        },
        concurrency: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Concurrency',
            default: 1
        },
        request_interval_seconds: {
            type: 'number',
            maximum: 60,
            minimum: 0.2,
            title: 'Request Interval Seconds',
            default: 1
        },
        publish_time: {
            type: 'integer',
            title: 'Publish Time',
            default: 0
        },
        media_processing_mode: {
            '$ref': '#/components/schemas/MediaProcessingMode',
            default: 'none'
        },
        media_storage: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MediaStorageBackend'
                },
                {
                    type: 'null'
                }
            ]
        },
        download_media: {
            type: 'boolean',
            title: 'Download Media',
            default: false
        },
        translate_subtitles: {
            type: 'boolean',
            title: 'Translate Subtitles',
            default: false
        },
        transcription_language: {
            type: 'string',
            maxLength: 32,
            minLength: 2,
            title: 'Transcription Language',
            default: 'auto'
        },
        account_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Id'
        },
        account_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            maxItems: 20,
            title: 'Account Ids'
        },
        account_pool_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Pool Id'
        },
        account_strategy: {
            '$ref': '#/components/schemas/DouyinAccountPoolStrategy',
            default: 'least_loaded'
        }
    },
    type: 'object',
    title: 'CrawlTaskCreate'
} as const;

export const CrawlTaskPhaseSchema = {
    type: 'string',
    enum: ['crawl', 'media', 'completed'],
    title: 'CrawlTaskPhase'
} as const;

export const CrawlTaskPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        account_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Id'
        },
        account_pool_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Pool Id'
        },
        account_strategy: {
            '$ref': '#/components/schemas/DouyinAccountPoolStrategy'
        },
        crawl_type: {
            '$ref': '#/components/schemas/DouyinCrawlType'
        },
        status: {
            '$ref': '#/components/schemas/CrawlTaskStatus'
        },
        request: {
            additionalProperties: true,
            type: 'object',
            title: 'Request'
        },
        aweme_count: {
            type: 'integer',
            title: 'Aweme Count'
        },
        comment_count: {
            type: 'integer',
            title: 'Comment Count'
        },
        action_count: {
            type: 'integer',
            title: 'Action Count'
        },
        checkpoint_phase: {
            '$ref': '#/components/schemas/CrawlTaskPhase'
        },
        resume_count: {
            type: 'integer',
            title: 'Resume Count'
        },
        can_resume_crawl: {
            type: 'boolean',
            title: 'Can Resume Crawl'
        },
        can_resume_media: {
            type: 'boolean',
            title: 'Can Resume Media'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        has_qrcode: {
            type: 'boolean',
            title: 'Has Qrcode'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        last_resumed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Resumed At'
        }
    },
    type: 'object',
    required: ['id', 'owner_id', 'account_id', 'account_pool_id', 'account_strategy', 'crawl_type', 'status', 'request', 'aweme_count', 'comment_count', 'action_count', 'checkpoint_phase', 'resume_count', 'can_resume_crawl', 'can_resume_media', 'error', 'has_qrcode', 'created_at', 'started_at', 'finished_at', 'last_resumed_at'],
    title: 'CrawlTaskPublic'
} as const;

export const CrawlTaskResumeRequestSchema = {
    properties: {
        resume_crawl: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Crawl'
        },
        resume_media: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Media'
        },
        cookies: {
            anyOf: [
                {
                    type: 'string',
                    format: 'password',
                    writeOnly: true
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cookies'
        }
    },
    type: 'object',
    title: 'CrawlTaskResumeRequest'
} as const;

export const CrawlTaskShardPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        account_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Id'
        },
        account_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Name'
        },
        shard_index: {
            type: 'integer',
            title: 'Shard Index'
        },
        status: {
            '$ref': '#/components/schemas/CrawlTaskShardStatus'
        },
        request: {
            additionalProperties: true,
            type: 'object',
            title: 'Request'
        },
        aweme_count: {
            type: 'integer',
            title: 'Aweme Count'
        },
        comment_count: {
            type: 'integer',
            title: 'Comment Count'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'task_id', 'account_id', 'account_name', 'shard_index', 'status', 'request', 'aweme_count', 'comment_count', 'error', 'started_at', 'finished_at', 'created_at'],
    title: 'CrawlTaskShardPublic'
} as const;

export const CrawlTaskShardStatusSchema = {
    type: 'string',
    enum: ['queued', 'running', 'succeeded', 'failed', 'interrupted', 'cancelled'],
    title: 'CrawlTaskShardStatus'
} as const;

export const CrawlTaskShardsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CrawlTaskShardPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CrawlTaskShardsPublic'
} as const;

export const CrawlTaskStatusSchema = {
    type: 'string',
    enum: ['queued', 'waiting_login', 'running', 'processing_media', 'cancelling', 'succeeded', 'failed', 'cancelled', 'interrupted'],
    title: 'CrawlTaskStatus'
} as const;

export const CrawlTasksPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CrawlTaskPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CrawlTasksPublic'
} as const;

export const DouyinAccountCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 80,
            minLength: 1,
            title: 'Name'
        },
        browser_mode: {
            '$ref': '#/components/schemas/DouyinBrowserMode',
            default: 'remote'
        },
        remote_slot: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remote Slot'
        },
        weight: {
            type: 'integer',
            maximum: 100,
            minimum: 1,
            title: 'Weight',
            default: 1
        },
        priority: {
            type: 'integer',
            maximum: 100,
            minimum: -100,
            title: 'Priority',
            default: 0
        },
        concurrency_limit: {
            type: 'integer',
            maximum: 3,
            minimum: 1,
            title: 'Concurrency Limit',
            default: 1
        },
        daily_task_limit: {
            type: 'integer',
            maximum: 10000,
            minimum: 1,
            title: 'Daily Task Limit',
            default: 100
        },
        min_request_interval_seconds: {
            type: 'number',
            maximum: 60,
            minimum: 0.2,
            title: 'Min Request Interval Seconds',
            default: 1
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DouyinAccountCreate'
} as const;

export const DouyinAccountLoginSessionPublicSchema = {
    properties: {
        account: {
            '$ref': '#/components/schemas/DouyinAccountPublic'
        },
        status: {
            '$ref': '#/components/schemas/DouyinAccountStatus'
        },
        browser_mode: {
            '$ref': '#/components/schemas/DouyinBrowserMode'
        },
        viewer_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Viewer Url'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['account', 'status', 'browser_mode', 'viewer_url', 'expires_at', 'message'],
    title: 'DouyinAccountLoginSessionPublic'
} as const;

export const DouyinAccountPoolCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 80,
            minLength: 1,
            title: 'Name'
        },
        description: {
            type: 'string',
            maxLength: 500,
            title: 'Description',
            default: ''
        },
        strategy: {
            '$ref': '#/components/schemas/DouyinAccountPoolStrategy',
            default: 'least_loaded'
        },
        max_parallel_accounts: {
            type: 'integer',
            maximum: 20,
            minimum: 1,
            title: 'Max Parallel Accounts',
            default: 2
        },
        account_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            maxItems: 20,
            title: 'Account Ids'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DouyinAccountPoolCreate'
} as const;

export const DouyinAccountPoolPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        strategy: {
            '$ref': '#/components/schemas/DouyinAccountPoolStrategy'
        },
        max_parallel_accounts: {
            type: 'integer',
            title: 'Max Parallel Accounts'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        accounts: {
            items: {
                '$ref': '#/components/schemas/DouyinAccountPublic'
            },
            type: 'array',
            title: 'Accounts'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'description', 'strategy', 'max_parallel_accounts', 'enabled', 'accounts', 'created_at', 'updated_at'],
    title: 'DouyinAccountPoolPublic'
} as const;

export const DouyinAccountPoolStrategySchema = {
    type: 'string',
    enum: ['least_loaded', 'weighted_round_robin'],
    title: 'DouyinAccountPoolStrategy'
} as const;

export const DouyinAccountPoolUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 80,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        strategy: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DouyinAccountPoolStrategy'
                },
                {
                    type: 'null'
                }
            ]
        },
        max_parallel_accounts: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 20,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Parallel Accounts'
        },
        account_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array',
                    maxItems: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Ids'
        },
        enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled'
        }
    },
    type: 'object',
    title: 'DouyinAccountPoolUpdate'
} as const;

export const DouyinAccountPoolsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DouyinAccountPoolPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DouyinAccountPoolsPublic'
} as const;

export const DouyinAccountPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        browser_mode: {
            '$ref': '#/components/schemas/DouyinBrowserMode'
        },
        remote_slot: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remote Slot'
        },
        status: {
            '$ref': '#/components/schemas/DouyinAccountStatus'
        },
        is_logged_in: {
            type: 'boolean',
            title: 'Is Logged In'
        },
        weight: {
            type: 'integer',
            title: 'Weight'
        },
        priority: {
            type: 'integer',
            title: 'Priority'
        },
        concurrency_limit: {
            type: 'integer',
            title: 'Concurrency Limit'
        },
        daily_task_limit: {
            type: 'integer',
            title: 'Daily Task Limit'
        },
        tasks_today: {
            type: 'integer',
            title: 'Tasks Today'
        },
        min_request_interval_seconds: {
            type: 'number',
            title: 'Min Request Interval Seconds'
        },
        active_leases: {
            type: 'integer',
            title: 'Active Leases'
        },
        failure_streak: {
            type: 'integer',
            title: 'Failure Streak'
        },
        cooldown_until: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooldown Until'
        },
        last_verified_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Verified At'
        },
        last_used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Used At'
        },
        last_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Error'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'browser_mode', 'remote_slot', 'status', 'is_logged_in', 'weight', 'priority', 'concurrency_limit', 'daily_task_limit', 'tasks_today', 'min_request_interval_seconds', 'active_leases', 'failure_streak', 'cooldown_until', 'last_verified_at', 'last_used_at', 'last_error', 'enabled', 'created_at', 'updated_at'],
    title: 'DouyinAccountPublic'
} as const;

export const DouyinAccountStatusSchema = {
    type: 'string',
    enum: ['login_required', 'verifying', 'ready', 'busy', 'cooldown', 'unhealthy', 'disabled'],
    title: 'DouyinAccountStatus'
} as const;

export const DouyinAccountUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 80,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        remote_slot: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remote Slot'
        },
        weight: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 100,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weight'
        },
        priority: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 100,
                    minimum: -100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        },
        concurrency_limit: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 3,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Concurrency Limit'
        },
        daily_task_limit: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10000,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Daily Task Limit'
        },
        min_request_interval_seconds: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 60,
                    minimum: 0.2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Request Interval Seconds'
        },
        enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled'
        }
    },
    type: 'object',
    title: 'DouyinAccountUpdate'
} as const;

export const DouyinAccountsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DouyinAccountPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DouyinAccountsPublic'
} as const;

export const DouyinAwemeCommentCrawlRequestSchema = {
    properties: {
        browser_mode: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DouyinBrowserMode'
                },
                {
                    type: 'null'
                }
            ]
        },
        cookies: {
            anyOf: [
                {
                    type: 'string',
                    format: 'password',
                    writeOnly: true
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cookies'
        },
        fetch_sub_comments: {
            type: 'boolean',
            title: 'Fetch Sub Comments',
            default: false
        },
        max_comments_per_aweme: {
            type: 'integer',
            maximum: 1000,
            minimum: 1,
            title: 'Max Comments Per Aweme',
            default: 10
        },
        concurrency: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Concurrency',
            default: 1
        },
        request_interval_seconds: {
            type: 'number',
            maximum: 60,
            minimum: 0.2,
            title: 'Request Interval Seconds',
            default: 1
        },
        account_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Id'
        }
    },
    type: 'object',
    title: 'DouyinAwemeCommentCrawlRequest'
} as const;

export const DouyinAwemeCreatorCrawlRequestSchema = {
    properties: {
        browser_mode: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DouyinBrowserMode'
                },
                {
                    type: 'null'
                }
            ]
        },
        cookies: {
            anyOf: [
                {
                    type: 'string',
                    format: 'password',
                    writeOnly: true
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cookies'
        },
        max_awemes: {
            type: 'integer',
            maximum: 1000,
            minimum: 1,
            title: 'Max Awemes',
            default: 20
        },
        fetch_comments: {
            type: 'boolean',
            title: 'Fetch Comments',
            default: false
        },
        fetch_sub_comments: {
            type: 'boolean',
            title: 'Fetch Sub Comments',
            default: false
        },
        max_comments_per_aweme: {
            type: 'integer',
            maximum: 1000,
            minimum: 1,
            title: 'Max Comments Per Aweme',
            default: 10
        },
        concurrency: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Concurrency',
            default: 1
        },
        request_interval_seconds: {
            type: 'number',
            maximum: 60,
            minimum: 0.2,
            title: 'Request Interval Seconds',
            default: 1
        },
        account_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Id'
        }
    },
    type: 'object',
    title: 'DouyinAwemeCreatorCrawlRequest'
} as const;

export const DouyinAwemePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        aweme_id: {
            type: 'string',
            title: 'Aweme Id'
        },
        aweme_type: {
            type: 'string',
            title: 'Aweme Type'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        create_time: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        creator_hash: {
            type: 'string',
            title: 'Creator Hash'
        },
        sec_uid: {
            type: 'string',
            title: 'Sec Uid'
        },
        nickname: {
            type: 'string',
            title: 'Nickname'
        },
        liked_count: {
            type: 'integer',
            title: 'Liked Count'
        },
        collected_count: {
            type: 'integer',
            title: 'Collected Count'
        },
        comment_count: {
            type: 'integer',
            title: 'Comment Count'
        },
        share_count: {
            type: 'integer',
            title: 'Share Count'
        },
        aweme_url: {
            type: 'string',
            title: 'Aweme Url'
        },
        cover_url: {
            type: 'string',
            title: 'Cover Url'
        },
        video_download_url: {
            type: 'string',
            title: 'Video Download Url'
        },
        music_download_url: {
            type: 'string',
            title: 'Music Download Url'
        },
        note_download_url: {
            type: 'string',
            title: 'Note Download Url'
        },
        source_keyword: {
            type: 'string',
            title: 'Source Keyword'
        },
        fetched_at: {
            type: 'string',
            format: 'date-time',
            title: 'Fetched At'
        }
    },
    type: 'object',
    required: ['id', 'task_id', 'aweme_id', 'aweme_type', 'title', 'description', 'create_time', 'creator_hash', 'sec_uid', 'nickname', 'liked_count', 'collected_count', 'comment_count', 'share_count', 'aweme_url', 'cover_url', 'video_download_url', 'music_download_url', 'note_download_url', 'source_keyword', 'fetched_at'],
    title: 'DouyinAwemePublic'
} as const;

export const DouyinAwemesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DouyinAwemePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DouyinAwemesPublic'
} as const;

export const DouyinBrowserModeSchema = {
    type: 'string',
    enum: ['local', 'remote'],
    title: 'DouyinBrowserMode'
} as const;

export const DouyinCommentExportRequestSchema = {
    properties: {
        aweme_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 1000,
            minItems: 1,
            title: 'Aweme Ids'
        }
    },
    type: 'object',
    required: ['aweme_ids'],
    title: 'DouyinCommentExportRequest'
} as const;

export const DouyinCommentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        comment_id: {
            type: 'string',
            title: 'Comment Id'
        },
        aweme_id: {
            type: 'string',
            title: 'Aweme Id'
        },
        parent_comment_id: {
            type: 'string',
            title: 'Parent Comment Id'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        create_time: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time'
        },
        creator_hash: {
            type: 'string',
            title: 'Creator Hash'
        },
        sec_uid: {
            type: 'string',
            title: 'Sec Uid'
        },
        nickname: {
            type: 'string',
            title: 'Nickname'
        },
        sub_comment_count: {
            type: 'integer',
            title: 'Sub Comment Count'
        },
        like_count: {
            type: 'integer',
            title: 'Like Count'
        },
        pictures: {
            type: 'string',
            title: 'Pictures'
        },
        fetched_at: {
            type: 'string',
            format: 'date-time',
            title: 'Fetched At'
        }
    },
    type: 'object',
    required: ['id', 'task_id', 'comment_id', 'aweme_id', 'parent_comment_id', 'content', 'create_time', 'creator_hash', 'sec_uid', 'nickname', 'sub_comment_count', 'like_count', 'pictures', 'fetched_at'],
    title: 'DouyinCommentPublic'
} as const;

export const DouyinCommentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DouyinCommentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DouyinCommentsPublic'
} as const;

export const DouyinCrawlTypeSchema = {
    type: 'string',
    enum: ['search', 'detail', 'creator', 'creator_from_aweme', 'liked', 'collected'],
    title: 'DouyinCrawlType'
} as const;

export const DouyinCreatorOptionPublicSchema = {
    properties: {
        creator_hash: {
            type: 'string',
            title: 'Creator Hash'
        },
        nickname: {
            type: 'string',
            title: 'Nickname'
        },
        work_count: {
            type: 'integer',
            title: 'Work Count'
        }
    },
    type: 'object',
    required: ['creator_hash', 'nickname', 'work_count'],
    title: 'DouyinCreatorOptionPublic'
} as const;

export const DouyinCreatorOptionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DouyinCreatorOptionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DouyinCreatorOptionsPublic'
} as const;

export const DouyinKeywordBatchModeSchema = {
    type: 'string',
    enum: ['combined', 'separate'],
    title: 'DouyinKeywordBatchMode'
} as const;

export const DouyinKeywordBatchTaskRequestSchema = {
    properties: {
        keyword_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            maxItems: 100,
            minItems: 1,
            title: 'Keyword Ids'
        },
        mode: {
            '$ref': '#/components/schemas/DouyinKeywordBatchMode',
            default: 'combined'
        },
        login_type: {
            '$ref': '#/components/schemas/DouyinLoginType',
            default: 'qrcode'
        },
        browser_mode: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DouyinBrowserMode'
                },
                {
                    type: 'null'
                }
            ]
        },
        start_page: {
            type: 'integer',
            minimum: 1,
            title: 'Start Page',
            default: 1
        },
        max_awemes: {
            type: 'integer',
            maximum: 1000,
            minimum: 1,
            title: 'Max Awemes',
            default: 10
        },
        fetch_comments: {
            type: 'boolean',
            title: 'Fetch Comments',
            default: true
        },
        fetch_sub_comments: {
            type: 'boolean',
            title: 'Fetch Sub Comments',
            default: false
        },
        max_comments_per_aweme: {
            type: 'integer',
            maximum: 1000,
            minimum: 1,
            title: 'Max Comments Per Aweme',
            default: 10
        },
        concurrency: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Concurrency',
            default: 1
        },
        request_interval_seconds: {
            type: 'number',
            maximum: 60,
            minimum: 0.2,
            title: 'Request Interval Seconds',
            default: 1
        },
        publish_time: {
            type: 'integer',
            title: 'Publish Time',
            default: 0
        },
        media_processing_mode: {
            '$ref': '#/components/schemas/MediaProcessingMode',
            default: 'none'
        },
        media_storage: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MediaStorageBackend'
                },
                {
                    type: 'null'
                }
            ]
        },
        download_media: {
            type: 'boolean',
            title: 'Download Media',
            default: false
        },
        translate_subtitles: {
            type: 'boolean',
            title: 'Translate Subtitles',
            default: false
        },
        transcription_language: {
            type: 'string',
            maxLength: 32,
            minLength: 2,
            title: 'Transcription Language',
            default: 'auto'
        },
        account_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Id'
        },
        account_pool_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Pool Id'
        },
        account_strategy: {
            '$ref': '#/components/schemas/DouyinAccountPoolStrategy',
            default: 'least_loaded'
        }
    },
    type: 'object',
    required: ['keyword_ids'],
    title: 'DouyinKeywordBatchTaskRequest'
} as const;

export const DouyinKeywordBulkCreateRequestSchema = {
    properties: {
        keywords: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 500,
            minItems: 1,
            title: 'Keywords'
        },
        notes: {
            type: 'string',
            maxLength: 1000,
            title: 'Notes',
            default: ''
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        }
    },
    type: 'object',
    required: ['keywords'],
    title: 'DouyinKeywordBulkCreateRequest'
} as const;

export const DouyinKeywordBulkCreateResultSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DouyinKeywordPublic'
            },
            type: 'array',
            title: 'Data'
        },
        created_count: {
            type: 'integer',
            title: 'Created Count'
        },
        existing_count: {
            type: 'integer',
            title: 'Existing Count'
        }
    },
    type: 'object',
    required: ['data', 'created_count', 'existing_count'],
    title: 'DouyinKeywordBulkCreateResult'
} as const;

export const DouyinKeywordPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        keyword: {
            type: 'string',
            title: 'Keyword'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        notes: {
            type: 'string',
            title: 'Notes'
        },
        status: {
            '$ref': '#/components/schemas/DouyinKeywordStatus'
        },
        task_count: {
            type: 'integer',
            title: 'Task Count'
        },
        active_task_count: {
            type: 'integer',
            title: 'Active Task Count'
        },
        success_task_count: {
            type: 'integer',
            title: 'Success Task Count'
        },
        failed_task_count: {
            type: 'integer',
            title: 'Failed Task Count'
        },
        aweme_count: {
            type: 'integer',
            title: 'Aweme Count'
        },
        last_task_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Task Id'
        },
        last_task_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CrawlTaskStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        last_crawled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Crawled At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'keyword', 'enabled', 'notes', 'status', 'task_count', 'active_task_count', 'success_task_count', 'failed_task_count', 'aweme_count', 'last_task_id', 'last_task_status', 'last_crawled_at', 'created_at', 'updated_at'],
    title: 'DouyinKeywordPublic'
} as const;

export const DouyinKeywordStatusSchema = {
    type: 'string',
    enum: ['unprocessed', 'active', 'crawled', 'failed'],
    title: 'DouyinKeywordStatus'
} as const;

export const DouyinKeywordSyncResultSchema = {
    properties: {
        task_count: {
            type: 'integer',
            title: 'Task Count'
        },
        keyword_count: {
            type: 'integer',
            title: 'Keyword Count'
        },
        created_count: {
            type: 'integer',
            title: 'Created Count'
        },
        binding_count: {
            type: 'integer',
            title: 'Binding Count'
        }
    },
    type: 'object',
    required: ['task_count', 'keyword_count', 'created_count', 'binding_count'],
    title: 'DouyinKeywordSyncResult'
} as const;

export const DouyinKeywordTaskBatchResultSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CrawlTaskPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DouyinKeywordTaskBatchResult'
} as const;

export const DouyinKeywordUpdateSchema = {
    properties: {
        keyword: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Keyword'
        },
        enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'DouyinKeywordUpdate'
} as const;

export const DouyinKeywordsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DouyinKeywordPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DouyinKeywordsPublic'
} as const;

export const DouyinLoginTypeSchema = {
    type: 'string',
    enum: ['qrcode', 'cookie'],
    title: 'DouyinLoginType'
} as const;

export const DouyinMediaAssetPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        aweme_id: {
            type: 'string',
            title: 'Aweme Id'
        },
        storage_backend: {
            '$ref': '#/components/schemas/MediaStorageBackend'
        },
        status: {
            '$ref': '#/components/schemas/MediaDownloadStatus'
        },
        progress: {
            type: 'integer',
            title: 'Progress'
        },
        attempt_count: {
            type: 'integer',
            title: 'Attempt Count'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type'
        },
        file_size: {
            type: 'integer',
            title: 'File Size'
        },
        sha256: {
            type: 'string',
            title: 'Sha256'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        download_available: {
            type: 'boolean',
            title: 'Download Available'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        migration_status: {
            '$ref': '#/components/schemas/MediaMigrationStatus'
        },
        migration_progress: {
            type: 'integer',
            title: 'Migration Progress'
        },
        migration_attempt_count: {
            type: 'integer',
            title: 'Migration Attempt Count'
        },
        migration_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Migration Error'
        },
        migration_started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Migration Started At'
        },
        migration_finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Migration Finished At'
        },
        subtitle: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DouyinSubtitlePublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'task_id', 'aweme_id', 'storage_backend', 'status', 'progress', 'attempt_count', 'mime_type', 'file_size', 'sha256', 'error', 'download_available', 'created_at', 'updated_at', 'completed_at', 'migration_status', 'migration_progress', 'migration_attempt_count', 'migration_error', 'migration_started_at', 'migration_finished_at', 'subtitle'],
    title: 'DouyinMediaAssetPublic'
} as const;

export const DouyinMediaAssetsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DouyinMediaAssetPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DouyinMediaAssetsPublic'
} as const;

export const DouyinMediaMigrationAcceptedSchema = {
    properties: {
        queued: {
            type: 'integer',
            title: 'Queued'
        },
        skipped: {
            type: 'integer',
            title: 'Skipped'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['queued', 'skipped', 'message'],
    title: 'DouyinMediaMigrationAccepted'
} as const;

export const DouyinMediaMigrationRequestSchema = {
    properties: {
        asset_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            maxItems: 1000,
            title: 'Asset Ids'
        }
    },
    type: 'object',
    title: 'DouyinMediaMigrationRequest'
} as const;

export const DouyinMediaProcessRequestSchema = {
    properties: {
        media_storage: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MediaStorageBackend'
                },
                {
                    type: 'null'
                }
            ]
        },
        translate_subtitles: {
            type: 'boolean',
            title: 'Translate Subtitles',
            default: false
        },
        force_retranslate: {
            type: 'boolean',
            title: 'Force Retranslate',
            default: false
        },
        transcription_language: {
            type: 'string',
            maxLength: 32,
            minLength: 2,
            title: 'Transcription Language',
            default: 'auto'
        },
        cookies: {
            anyOf: [
                {
                    type: 'string',
                    format: 'password',
                    writeOnly: true
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cookies'
        }
    },
    type: 'object',
    title: 'DouyinMediaProcessRequest'
} as const;

export const DouyinMediaRetryRequestSchema = {
    properties: {
        asset_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            maxItems: 1000,
            title: 'Asset Ids'
        },
        retry_downloads: {
            type: 'boolean',
            title: 'Retry Downloads',
            default: true
        },
        retry_subtitles: {
            type: 'boolean',
            title: 'Retry Subtitles',
            default: true
        },
        force_retranslate: {
            type: 'boolean',
            title: 'Force Retranslate',
            default: false
        }
    },
    type: 'object',
    title: 'DouyinMediaRetryRequest'
} as const;

export const DouyinMediaSummaryPublicSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        queued: {
            type: 'integer',
            title: 'Queued'
        },
        downloading: {
            type: 'integer',
            title: 'Downloading'
        },
        downloaded: {
            type: 'integer',
            title: 'Downloaded'
        },
        download_failed: {
            type: 'integer',
            title: 'Download Failed'
        },
        subtitle_pending: {
            type: 'integer',
            title: 'Subtitle Pending'
        },
        subtitle_running: {
            type: 'integer',
            title: 'Subtitle Running'
        },
        subtitle_completed: {
            type: 'integer',
            title: 'Subtitle Completed'
        },
        subtitle_failed: {
            type: 'integer',
            title: 'Subtitle Failed'
        },
        local_downloaded: {
            type: 'integer',
            title: 'Local Downloaded'
        },
        minio_downloaded: {
            type: 'integer',
            title: 'Minio Downloaded'
        },
        migration_queued: {
            type: 'integer',
            title: 'Migration Queued'
        },
        migration_running: {
            type: 'integer',
            title: 'Migration Running'
        },
        migration_cleanup_pending: {
            type: 'integer',
            title: 'Migration Cleanup Pending'
        },
        migration_completed: {
            type: 'integer',
            title: 'Migration Completed'
        },
        migration_failed: {
            type: 'integer',
            title: 'Migration Failed'
        }
    },
    type: 'object',
    required: ['total', 'queued', 'downloading', 'downloaded', 'download_failed', 'subtitle_pending', 'subtitle_running', 'subtitle_completed', 'subtitle_failed', 'local_downloaded', 'minio_downloaded', 'migration_queued', 'migration_running', 'migration_cleanup_pending', 'migration_completed', 'migration_failed'],
    title: 'DouyinMediaSummaryPublic'
} as const;

export const DouyinSubtitleExportFormatSchema = {
    type: 'string',
    enum: ['txt', 'srt', 'vtt'],
    title: 'DouyinSubtitleExportFormat'
} as const;

export const DouyinSubtitleExportRequestSchema = {
    properties: {
        aweme_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 1000,
            minItems: 1,
            title: 'Aweme Ids'
        },
        format: {
            '$ref': '#/components/schemas/DouyinSubtitleExportFormat',
            default: 'srt'
        }
    },
    type: 'object',
    required: ['aweme_ids'],
    title: 'DouyinSubtitleExportRequest'
} as const;

export const DouyinSubtitlePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        asset_id: {
            type: 'string',
            format: 'uuid',
            title: 'Asset Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        aweme_id: {
            type: 'string',
            title: 'Aweme Id'
        },
        status: {
            '$ref': '#/components/schemas/SubtitleStatus'
        },
        progress: {
            type: 'integer',
            title: 'Progress'
        },
        attempt_count: {
            type: 'integer',
            title: 'Attempt Count'
        },
        requested_backend: {
            type: 'string',
            title: 'Requested Backend'
        },
        actual_backend: {
            type: 'string',
            title: 'Actual Backend'
        },
        model: {
            type: 'string',
            title: 'Model'
        },
        language: {
            type: 'string',
            title: 'Language'
        },
        duration_seconds: {
            type: 'number',
            title: 'Duration Seconds'
        },
        full_text: {
            type: 'string',
            title: 'Full Text'
        },
        segments: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Segments'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        }
    },
    type: 'object',
    required: ['id', 'asset_id', 'task_id', 'aweme_id', 'status', 'progress', 'attempt_count', 'requested_backend', 'actual_backend', 'model', 'language', 'duration_seconds', 'full_text', 'segments', 'error', 'created_at', 'started_at', 'finished_at'],
    title: 'DouyinSubtitlePublic'
} as const;

export const DouyinUserActionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        account_hash: {
            type: 'string',
            title: 'Account Hash'
        },
        aweme_id: {
            type: 'string',
            title: 'Aweme Id'
        },
        action_type: {
            type: 'string',
            title: 'Action Type'
        },
        observed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Observed At'
        }
    },
    type: 'object',
    required: ['id', 'task_id', 'account_hash', 'aweme_id', 'action_type', 'observed_at'],
    title: 'DouyinUserActionPublic'
} as const;

export const DouyinUserActionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DouyinUserActionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DouyinUserActionsPublic'
} as const;

export const DouyinWorkPublicSchema = {
    properties: {
        aweme: {
            '$ref': '#/components/schemas/DouyinAwemePublic'
        },
        persisted_comment_count: {
            type: 'integer',
            title: 'Persisted Comment Count'
        },
        media: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DouyinMediaAssetPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['aweme', 'persisted_comment_count', 'media'],
    title: 'DouyinWorkPublic'
} as const;

export const DouyinWorksPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DouyinWorkPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DouyinWorksPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MediaDownloadStatusSchema = {
    type: 'string',
    enum: ['queued', 'downloading', 'downloaded', 'failed'],
    title: 'MediaDownloadStatus'
} as const;

export const MediaMigrationStatusSchema = {
    type: 'string',
    enum: ['idle', 'queued', 'uploading', 'verifying', 'switching', 'cleanup_pending', 'completed', 'failed'],
    title: 'MediaMigrationStatus'
} as const;

export const MediaProcessingModeSchema = {
    type: 'string',
    enum: ['none', 'immediate', 'batch'],
    title: 'MediaProcessingMode'
} as const;

export const MediaStorageBackendSchema = {
    type: 'string',
    enum: ['local', 'minio'],
    title: 'MediaStorageBackend'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SubtitleStatusSchema = {
    type: 'string',
    enum: ['pending', 'running', 'completed', 'failed'],
    title: 'SubtitleStatus'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;