// This file is auto-generated by @hey-api/openapi-ts

/**
 * 单个 HTTP API 操作的文档视图模型。
 */
export type ApiOperationDocPublic = {
    method: string;
    path: string;
    summary: string;
    description: string;
    operation_id: string;
    tags: Array<(string)>;
    auth_required: boolean;
    parameters: Array<{
        [key: string]: unknown;
    }>;
    request_body: ({
    [key: string]: unknown;
} | null);
    response_codes: Array<(string)>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * 批量删除已结束采集任务的请求体。
 */
export type CrawlTaskBulkDeleteRequest = {
    ids: Array<(string)>;
};

/**
 * 批量恢复任务的受理结果。
 */
export type CrawlTaskBulkResumePublic = {
    data: Array<CrawlTaskPublic>;
    count: number;
    failures: Array<CrawlTaskResumeFailure>;
    failed_count: number;
};

/**
 * 批量恢复失效采集任务的请求体。
 */
export type CrawlTaskBulkResumeRequest = {
    ids: Array<(string)>;
    task_interval_seconds?: (number | null);
};

/**
 * 创建抖音爬取任务的请求模型（HTTP/MCP 入参）。
 *
 * 校验爬取目标与登录方式的一致性，并对评论开关、媒体下载、字幕翻译等选项做联动修正；
 * cookies 使用 SecretStr 存储，序列化与日志输出时自动脱敏。
 */
export type CrawlTaskCreate = {
    track_id?: (string | null);
    crawl_type?: DouyinCrawlType;
    login_type?: DouyinLoginType;
    browser_mode?: (DouyinBrowserMode | null);
    cookies?: (string | null);
    keywords?: Array<(string)>;
    video_ids?: Array<(string)>;
    comment_source_task_id?: (string | null);
    creator_ids?: Array<(string)>;
    start_page?: number;
    max_awemes?: number;
    fetch_comments?: boolean;
    fetch_sub_comments?: boolean;
    max_comments_per_aweme?: number;
    concurrency?: number;
    request_delay_level?: DouyinRequestDelayLevel;
    request_interval_seconds?: number;
    task_interval_seconds?: (number | null);
    publish_time?: number;
    media_processing_mode?: MediaProcessingMode;
    media_storage?: (MediaStorageBackend | null);
    download_media?: boolean;
    translate_subtitles?: boolean;
    subtitle_only?: boolean;
    transcription_language?: string;
    account_id?: (string | null);
    account_ids?: Array<(string)>;
    account_pool_id?: (string | null);
    account_strategy?: DouyinAccountPoolStrategy;
};

/**
 * 任务断点所处的执行阶段（恢复时据此判断从哪一步继续）。
 */
export type CrawlTaskPhase = 'crawl' | 'media' | 'completed';

/**
 * 爬取任务对外展示模型（含赛道信息、代表性作品与可恢复性标记）。
 */
export type CrawlTaskPublic = {
    id: string;
    owner_id: string;
    track_id: string;
    track_name: string;
    track_is_default: boolean;
    account_id: (string | null);
    account_name: (string | null);
    account_pool_id: (string | null);
    account_pool_name: (string | null);
    account_strategy: DouyinAccountPoolStrategy;
    crawl_type: DouyinCrawlType;
    status: CrawlTaskStatus;
    request: {
        [key: string]: unknown;
    };
    display_title?: (string | null);
    display_author?: (string | null);
    creator_names?: Array<(string)>;
    source_type?: DouyinSourceType;
    source_names?: Array<(string)>;
    source_label?: string;
    display_aweme_id?: (string | null);
    aweme_count: number;
    comment_count: number;
    action_count: number;
    checkpoint_phase: CrawlTaskPhase;
    resume_count: number;
    can_resume_crawl: boolean;
    can_resume_media: boolean;
    error: (string | null);
    has_qrcode: boolean;
    created_at: string;
    started_at: (string | null);
    finished_at: (string | null);
    last_resumed_at: (string | null);
};

/**
 * 批量恢复中单个任务未能受理时的错误明细。
 */
export type CrawlTaskResumeFailure = {
    task_id: string;
    error: string;
};

/**
 * 恢复（继续执行）已终止任务的请求模型。
 */
export type CrawlTaskResumeRequest = {
    resume_crawl?: (boolean | null);
    resume_media?: (boolean | null);
    cookies?: (string | null);
    account_id?: (string | null);
    task_interval_seconds?: (number | null);
};

/**
 * 任务分片对外展示模型。
 */
export type CrawlTaskShardPublic = {
    id: string;
    task_id: string;
    account_id: (string | null);
    account_name: (string | null);
    shard_index: number;
    status: CrawlTaskShardStatus;
    request: {
        [key: string]: unknown;
    };
    aweme_count: number;
    comment_count: number;
    error: (string | null);
    started_at: (string | null);
    finished_at: (string | null);
    created_at: string;
};

/**
 * 任务分片列表响应。
 */
export type CrawlTaskShardsPublic = {
    data: Array<CrawlTaskShardPublic>;
    count: number;
};

/**
 * 任务分片（多账号并行时单个账号负责的子任务）的状态机。
 */
export type CrawlTaskShardStatus = 'queued' | 'running' | 'succeeded' | 'failed' | 'interrupted' | 'cancelled';

/**
 * 爬取任务分页列表响应。
 */
export type CrawlTasksPublic = {
    data: Array<CrawlTaskPublic>;
    count: number;
};

/**
 * 爬取任务状态机（后五个为终态或近终态）。
 */
export type CrawlTaskStatus = 'queued' | 'waiting_login' | 'running' | 'processing_media' | 'cancelling' | 'succeeded' | 'failed' | 'cancelled' | 'interrupted';

/**
 * 创建抖音账号的请求模型。
 */
export type DouyinAccountCreate = {
    name: string;
    browser_mode?: DouyinBrowserMode;
    remote_slot?: (string | null);
    weight?: number;
    priority?: number;
    concurrency_limit?: number;
    daily_task_limit?: number;
    min_request_interval_seconds?: number;
};

/**
 * 开启账号登录会话的响应模型。
 */
export type DouyinAccountLoginSessionPublic = {
    account: DouyinAccountPublic;
    status: DouyinAccountStatus;
    browser_mode: DouyinBrowserMode;
    viewer_url: (string | null);
    expires_at: string;
    message: string;
};

/**
 * 创建账号池的请求模型。
 */
export type DouyinAccountPoolCreate = {
    name: string;
    description?: string;
    strategy?: DouyinAccountPoolStrategy;
    max_parallel_accounts?: number;
    account_ids?: Array<(string)>;
};

/**
 * 账号池对外响应模型（含成员账号摘要）。
 */
export type DouyinAccountPoolPublic = {
    id: string;
    name: string;
    description: string;
    strategy: DouyinAccountPoolStrategy;
    max_parallel_accounts: number;
    enabled: boolean;
    accounts: Array<DouyinAccountPublic>;
    created_at: string;
    updated_at: string;
};

/**
 * 账号池列表响应。
 */
export type DouyinAccountPoolsPublic = {
    data: Array<DouyinAccountPoolPublic>;
    count: number;
};

/**
 * 账号池的账号调度策略。
 */
export type DouyinAccountPoolStrategy = 'least_loaded' | 'round_robin' | 'weighted_round_robin';

/**
 * 更新账号池的请求模型，所有字段可选。
 */
export type DouyinAccountPoolUpdate = {
    name?: (string | null);
    description?: (string | null);
    strategy?: (DouyinAccountPoolStrategy | null);
    max_parallel_accounts?: (number | null);
    account_ids?: (Array<(string)> | null);
    enabled?: (boolean | null);
};

/**
 * 账号对外响应模型（不包含 identity_hash、profile_key 等内部字段）。
 */
export type DouyinAccountPublic = {
    id: string;
    name: string;
    browser_mode: DouyinBrowserMode;
    remote_slot: (string | null);
    status: DouyinAccountStatus;
    is_logged_in: boolean;
    weight: number;
    priority: number;
    concurrency_limit: number;
    daily_task_limit: number;
    tasks_today: number;
    min_request_interval_seconds: number;
    active_leases: number;
    failure_streak: number;
    cooldown_until: (string | null);
    last_verified_at: (string | null);
    last_used_at: (string | null);
    last_error: (string | null);
    enabled: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * 账号分页列表响应。
 */
export type DouyinAccountsPublic = {
    data: Array<DouyinAccountPublic>;
    count: number;
};

/**
 * 抖音账号生命周期状态，调度器据此判断账号是否可被选中执行任务。
 */
export type DouyinAccountStatus = 'login_required' | 'verifying' | 'ready' | 'busy' | 'cooldown' | 'unhealthy' | 'disabled';

/**
 * 更新抖音账号的请求模型，所有字段可选，仅更新显式传入的字段。
 */
export type DouyinAccountUpdate = {
    name?: (string | null);
    remote_slot?: (string | null);
    weight?: (number | null);
    priority?: (number | null);
    concurrency_limit?: (number | null);
    daily_task_limit?: (number | null);
    min_request_interval_seconds?: (number | null);
    enabled?: (boolean | null);
};

/**
 * 针对单个作品重新采集评论的任务创建请求体。
 */
export type DouyinAwemeCommentCrawlRequest = {
    browser_mode?: (DouyinBrowserMode | null);
    cookies?: (string | null);
    fetch_sub_comments?: boolean;
    max_comments_per_aweme?: number;
    concurrency?: number;
    request_delay_level?: DouyinRequestDelayLevel;
    request_interval_seconds?: number;
    account_id?: (string | null);
};

/**
 * 按创作者主页批量采集作品的请求模型。
 */
export type DouyinAwemeCreatorCrawlRequest = {
    browser_mode?: (DouyinBrowserMode | null);
    cookies?: (string | null);
    max_awemes?: number;
    fetch_comments?: boolean;
    fetch_sub_comments?: boolean;
    max_comments_per_aweme?: number;
    concurrency?: number;
    request_delay_level?: DouyinRequestDelayLevel;
    request_interval_seconds?: number;
    account_id?: (string | null);
};

/**
 * 作品对外响应模型。
 */
export type DouyinAwemePublic = {
    id: string;
    task_id: string;
    aweme_id: string;
    aweme_type: string;
    title: string;
    description: string;
    create_time: (number | null);
    creator_hash: string;
    sec_uid: string;
    nickname: string;
    liked_count: number;
    collected_count: number;
    comment_count: number;
    share_count: number;
    aweme_url: string;
    cover_url: string;
    video_download_url: string;
    music_download_url: string;
    note_download_url: string;
    source_keyword: string;
    fetched_at: string;
    source_type?: (DouyinSourceType | null);
    source_name?: (string | null);
    source_label?: (string | null);
};

/**
 * 作品分页列表响应。
 */
export type DouyinAwemesPublic = {
    data: Array<DouyinAwemePublic>;
    count: number;
};

/**
 * 从历史采集作品导入占位达人的结果统计。
 */
export type DouyinAwemeSyncResult = {
    total_count: number;
    created_count: number;
    existing_count: number;
};

/**
 * 批量创建视频评论互动任务的请求模型。
 */
export type DouyinBatchCommentCreate = {
    targets: Array<DouyinBatchCommentTarget>;
    comments: Array<(string)>;
    mode?: DouyinBatchCommentMode;
    account_id?: (string | null);
    account_pool_id?: (string | null);
    account_strategy?: DouyinAccountPoolStrategy;
    filter_recently_commented?: boolean;
    delay_min_seconds?: number;
    delay_max_seconds?: number;
};

/**
 * 批量评论内容分配方式。
 */
export type DouyinBatchCommentMode = 'one_per_video' | 'all_per_video';

/**
 * 批量评论创建结果。
 */
export type DouyinBatchCommentPublic = {
    batch_id: string;
    interaction_ids: Array<(string)>;
    selected_target_count: number;
    filtered_target_count: number;
    submitted_target_count: number;
    total_count: number;
    message: string;
};

/**
 * 批量评论的一个视频目标。
 */
export type DouyinBatchCommentTarget = {
    task_id: string;
    aweme_id: string;
};

/**
 * 账号关联浏览器的运行模式。
 */
export type DouyinBrowserMode = 'local' | 'remote';

/**
 * 远程浏览器槽位的占用与健康状态，供槽位管理页展示。
 */
export type DouyinBrowserSlotPublic = {
    name: (string | null);
    label: string;
    is_default: boolean;
    available: boolean;
    configured: boolean;
    viewer_available: boolean;
    viewer_url: (string | null);
    cdp_healthy: boolean;
    page_count: number;
    active_page_title: (string | null);
    active_page_url: (string | null);
    latency_ms: (number | null);
    checked_at: string;
    occupied_account_id: (string | null);
    occupied_account_name: (string | null);
};

/**
 * 远程浏览器槽位列表响应。
 */
export type DouyinBrowserSlotsPublic = {
    data: Array<DouyinBrowserSlotPublic>;
    count: number;
};

/**
 * 批量删除请求体（按记录 ID）。
 */
export type DouyinBulkDeleteRequest = {
    ids: Array<(string)>;
};

/**
 * 按作品号批量导出评论的请求体。
 */
export type DouyinCommentExportRequest = {
    aweme_ids: Array<(string)>;
};

/**
 * 评论库列表项，聚合评论、所属作品与任务状态信息。
 */
export type DouyinCommentLibraryItemPublic = {
    comment: DouyinCommentPublic;
    aweme: DouyinAwemePublic;
    track_id: string;
    track_name: string;
    task_title: string;
    task_status: CrawlTaskStatus;
    task_created_at: string;
};

/**
 * 评论库分页查询响应模型，附带统计汇总。
 */
export type DouyinCommentLibraryPublic = {
    data: Array<DouyinCommentLibraryItemPublic>;
    count: number;
    summary: DouyinCommentLibrarySummaryPublic;
};

/**
 * 评论库筛选结果的全量统计汇总（不受分页影响）。
 */
export type DouyinCommentLibrarySummaryPublic = {
    matched_count: number;
    top_level_count: number;
    reply_count: number;
    picture_count: number;
    total_like_count: number;
};

/**
 * 单条评论的对外展示模型，字段与 DouyinComment 实体一一对应。
 */
export type DouyinCommentPublic = {
    id: string;
    task_id: string;
    comment_id: string;
    aweme_id: string;
    parent_comment_id: string;
    content: string;
    create_time: (number | null);
    creator_hash: string;
    sec_uid: string;
    nickname: string;
    sub_comment_count: number;
    like_count: number;
    pictures: string;
    fetched_at: string;
};

/**
 * 评论精选导出请求体，按评论记录 ID 导出。
 */
export type DouyinCommentSelectionExportRequest = {
    comment_ids: Array<(string)>;
};

/**
 * 评论分页列表响应模型。
 */
export type DouyinCommentsPublic = {
    data: Array<DouyinCommentPublic>;
    count: number;
};

/**
 * 抖音爬取类型。
 */
export type DouyinCrawlType = 'search' | 'detail' | 'creator' | 'creator_from_aweme' | 'liked' | 'collected';

/**
 * 达人批量创建采集任务的请求体。
 */
export type DouyinCreatorBatchTaskRequest = {
    creator_ids: Array<(string)>;
    track_id?: (string | null);
    mode?: string;
    login_type?: DouyinLoginType;
    browser_mode?: (DouyinBrowserMode | null);
    cookies?: (string | null);
    start_page?: number;
    max_awemes?: number;
    fetch_comments?: boolean;
    fetch_sub_comments?: boolean;
    max_comments_per_aweme?: number;
    concurrency?: number;
    request_delay_level?: DouyinRequestDelayLevel;
    request_interval_seconds?: number;
    task_interval_seconds?: (number | null);
    publish_time?: number;
    media_processing_mode?: MediaProcessingMode;
    media_storage?: (MediaStorageBackend | null);
    download_media?: boolean;
    translate_subtitles?: boolean;
    transcription_language?: string;
    account_id?: (string | null);
    account_ids?: Array<(string)>;
    account_pool_id?: (string | null);
    account_strategy?: DouyinAccountPoolStrategy;
};

/**
 * 批量创建达人请求体。
 */
export type DouyinCreatorBulkCreateRequest = {
    creators: Array<(string)>;
    track_id?: (string | null);
    notes?: string;
    enabled?: boolean;
};

/**
 * 批量创建达人的结果响应。
 */
export type DouyinCreatorBulkCreateResult = {
    data: Array<DouyinCreatorPublic>;
    created_count: number;
    existing_count: number;
};

/**
 * 创作者选项（前端下拉选择用）。
 */
export type DouyinCreatorOptionPublic = {
    creator_hash: string;
    nickname: string;
    work_count: number;
};

/**
 * 创作者选项列表响应。
 */
export type DouyinCreatorOptionsPublic = {
    data: Array<DouyinCreatorOptionPublic>;
    count: number;
};

/**
 * 达人对外展示模型，聚合所属赛道信息与关联任务的统计汇总。
 */
export type DouyinCreatorPublic = {
    id: string;
    track_id: string;
    track_name: string;
    track_is_default: boolean;
    sec_uid: string;
    creator_hash: string;
    nickname: string;
    enabled: boolean;
    is_placeholder: boolean;
    notes: string;
    status: DouyinCreatorStatus;
    task_count: number;
    active_task_count: number;
    success_task_count: number;
    failed_task_count: number;
    aweme_count: number;
    last_task_id: (string | null);
    last_task_status: (CrawlTaskStatus | null);
    last_crawled_at: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * 达人分页列表响应模型。
 */
export type DouyinCreatorsPublic = {
    data: Array<DouyinCreatorPublic>;
    count: number;
};

/**
 * 达人处理状态（由关联任务状态聚合推导得出，不落库）。
 */
export type DouyinCreatorStatus = 'unprocessed' | 'active' | 'crawled' | 'failed';

/**
 * 达人同步（单任务或历史回填）的结果统计。
 */
export type DouyinCreatorSyncResult = {
    task_count: number;
    creator_count: number;
    created_count: number;
    binding_count: number;
};

/**
 * 达人批量建任务的结果响应。
 */
export type DouyinCreatorTaskBatchResult = {
    data: Array<CrawlTaskPublic>;
    count: number;
};

/**
 * 达人更新请求体，所有字段可选，仅更新传入的字段。
 *
 * sec_uid 仅用于补全待补全占位达人：服务端会校验新主页与
 * creator_hash 的脱敏哈希一致，通过后达人转为正式状态。
 */
export type DouyinCreatorUpdate = {
    nickname?: (string | null);
    track_id?: (string | null);
    enabled?: (boolean | null);
    notes?: (string | null);
    sec_uid?: (string | null);
};

/**
 * 创建互动任务的请求模型。
 */
export type DouyinInteractionCreate = {
    task_id: string;
    aweme_id: string;
    account_id: string;
    interaction_type: DouyinInteractionType;
    target_comment_id?: (string | null);
    content: string;
};

/**
 * 互动任务详情的对外模型，包含解密后的完整内容与事件时间线。
 */
export type DouyinInteractionDetailPublic = {
    id: string;
    task_id: string;
    source_type?: DouyinSourceType;
    source_names?: Array<(string)>;
    source_label?: string;
    batch_id: (string | null);
    sequence_index: (number | null);
    scheduled_at: (string | null);
    account_id: (string | null);
    account_pool_id: (string | null);
    account_name: string;
    aweme_id: string;
    target_video_url: string;
    target_comment_id: (string | null);
    target_comment_content: (string | null);
    interaction_type: DouyinInteractionType;
    content_preview: string;
    status: DouyinInteractionStatus;
    failure_code: (string | null);
    error: (string | null);
    attempt_count: number;
    result_platform_id: (string | null);
    human_confirmed_at: (string | null);
    started_at: (string | null);
    finished_at: (string | null);
    created_at: string;
    updated_at: string;
    can_confirm: boolean;
    can_retry: boolean;
    can_cancel: boolean;
    content: string;
    events: Array<DouyinInteractionEventPublic>;
};

/**
 * 互动事件的对外模型。
 */
export type DouyinInteractionEventPublic = {
    id: string;
    event: string;
    from_status: (DouyinInteractionStatus | null);
    to_status: DouyinInteractionStatus;
    detail: (string | null);
    attempt_number: number;
    has_screenshot: boolean;
    created_at: string;
};

/**
 * 互动发送前预检结果的对外模型。
 */
export type DouyinInteractionPreflightPublic = {
    allowed: boolean;
    failure_code?: (string | null);
    message: string;
    account_name: string;
    remaining_daily_quota: number;
    cooldown_until?: (string | null);
    duplicate_interaction_id?: (string | null);
};

/**
 * 互动任务的对外列表/概要模型。
 */
export type DouyinInteractionPublic = {
    id: string;
    task_id: string;
    source_type?: DouyinSourceType;
    source_names?: Array<(string)>;
    source_label?: string;
    batch_id: (string | null);
    sequence_index: (number | null);
    scheduled_at: (string | null);
    account_id: (string | null);
    account_pool_id: (string | null);
    account_name: string;
    aweme_id: string;
    target_video_url: string;
    target_comment_id: (string | null);
    target_comment_content: (string | null);
    interaction_type: DouyinInteractionType;
    content_preview: string;
    status: DouyinInteractionStatus;
    failure_code: (string | null);
    error: (string | null);
    attempt_count: number;
    result_platform_id: (string | null);
    human_confirmed_at: (string | null);
    started_at: (string | null);
    finished_at: (string | null);
    created_at: string;
    updated_at: string;
    can_confirm: boolean;
    can_retry: boolean;
    can_cancel: boolean;
};

/**
 * 账号互动配额的对外模型。
 */
export type DouyinInteractionQuotaPublic = {
    account_id: string;
    account_name: string;
    daily_limit: number;
    used_today: number;
    remaining_today: number;
    min_interval_seconds: number;
    cooldown_until: (string | null);
    available: boolean;
};

/**
 * 互动重试请求模型。
 */
export type DouyinInteractionRetryRequest = {
    confirm_not_sent?: boolean;
};

/**
 * 互动任务分页列表的对外模型。
 */
export type DouyinInteractionsPublic = {
    data: Array<DouyinInteractionPublic>;
    count: number;
};

/**
 * 抖音互动任务状态机枚举。
 */
export type DouyinInteractionStatus = 'pending_confirmation' | 'queued' | 'running' | 'succeeded' | 'failed' | 'blocked' | 'needs_review' | 'cancelled';

/**
 * 抖音互动类型枚举。
 */
export type DouyinInteractionType = 'video_comment' | 'comment_reply' | 'creator_message';

/**
 * 关键词批量建任务的分组模式。
 */
export type DouyinKeywordBatchMode = 'combined' | 'separate';

/**
 * 关键词批量创建采集任务的请求体。
 */
export type DouyinKeywordBatchTaskRequest = {
    keyword_ids: Array<(string)>;
    track_id?: (string | null);
    mode?: DouyinKeywordBatchMode;
    login_type?: DouyinLoginType;
    browser_mode?: (DouyinBrowserMode | null);
    start_page?: number;
    max_awemes?: number;
    fetch_comments?: boolean;
    fetch_sub_comments?: boolean;
    max_comments_per_aweme?: number;
    concurrency?: number;
    request_delay_level?: DouyinRequestDelayLevel;
    request_interval_seconds?: number;
    task_interval_seconds?: (number | null);
    publish_time?: number;
    media_processing_mode?: MediaProcessingMode;
    media_storage?: (MediaStorageBackend | null);
    download_media?: boolean;
    translate_subtitles?: boolean;
    transcription_language?: string;
    account_id?: (string | null);
    account_ids?: Array<(string)>;
    account_pool_id?: (string | null);
    account_strategy?: DouyinAccountPoolStrategy;
};

/**
 * 批量创建关键词请求体。
 */
export type DouyinKeywordBulkCreateRequest = {
    keywords: Array<(string)>;
    track_id?: (string | null);
    notes?: string;
    category?: string;
    enabled?: boolean;
};

/**
 * 批量创建关键词的结果响应。
 */
export type DouyinKeywordBulkCreateResult = {
    data: Array<DouyinKeywordPublic>;
    created_count: number;
    existing_count: number;
};

/**
 * 关键词对外展示模型，聚合所属赛道信息与关联任务的统计汇总。
 */
export type DouyinKeywordPublic = {
    id: string;
    track_id: string;
    track_name: string;
    track_is_default: boolean;
    keyword: string;
    enabled: boolean;
    category: string;
    notes: string;
    status: DouyinKeywordStatus;
    task_count: number;
    active_task_count: number;
    success_task_count: number;
    failed_task_count: number;
    aweme_count: number;
    last_task_id: (string | null);
    last_task_status: (CrawlTaskStatus | null);
    last_crawled_at: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * 关键词分页列表响应模型。
 */
export type DouyinKeywordsPublic = {
    data: Array<DouyinKeywordPublic>;
    count: number;
};

/**
 * 关键词处理状态（由关联任务状态聚合推导得出，不落库）。
 */
export type DouyinKeywordStatus = 'unprocessed' | 'active' | 'crawled' | 'failed';

/**
 * 关键词同步（单任务或历史回填）的结果统计。
 */
export type DouyinKeywordSyncResult = {
    task_count: number;
    keyword_count: number;
    created_count: number;
    binding_count: number;
};

/**
 * 关键词批量建任务的结果响应。
 */
export type DouyinKeywordTaskBatchResult = {
    data: Array<CrawlTaskPublic>;
    count: number;
};

/**
 * 关键词更新请求体，所有字段可选，仅更新传入的字段。
 */
export type DouyinKeywordUpdate = {
    keyword?: (string | null);
    track_id?: (string | null);
    enabled?: (boolean | null);
    category?: (string | null);
    notes?: (string | null);
};

/**
 * 按媒体库筛选条件批量触发本地到 MinIO 迁移的请求体。
 */
export type DouyinLibraryMediaMigrationRequest = {
    search?: (string | null);
    task_id?: (string | null);
    track_id?: (string | null);
    creator_hash?: (string | null);
    tag_id?: (string | null);
    subtitle_status?: 'all' | 'pending' | 'running' | 'completed' | 'failed';
};

export type subtitle_status = 'all' | 'pending' | 'running' | 'completed' | 'failed';

/**
 * 抖音登录方式。
 */
export type DouyinLoginType = 'qrcode' | 'cookie';

/**
 * 媒体资产的对外只读视图，附带其字幕记录。
 */
export type DouyinMediaAssetPublic = {
    id: string;
    task_id: string;
    aweme_id: string;
    storage_backend: MediaStorageBackend;
    status: MediaDownloadStatus;
    progress: number;
    attempt_count: number;
    mime_type: string;
    file_size: number;
    sha256: string;
    error: (string | null);
    download_available: boolean;
    created_at: string;
    updated_at: string;
    completed_at: (string | null);
    migration_status: MediaMigrationStatus;
    migration_progress: number;
    migration_attempt_count: number;
    migration_error: (string | null);
    migration_started_at: (string | null);
    migration_finished_at: (string | null);
    subtitle: (DouyinSubtitlePublic | null);
};

/**
 * 媒体资产分页列表响应。
 */
export type DouyinMediaAssetsPublic = {
    data: Array<DouyinMediaAssetPublic>;
    count: number;
};

/**
 * 迁移请求受理结果。
 */
export type DouyinMediaMigrationAccepted = {
    queued: number;
    skipped: number;
    message: string;
};

/**
 * 按资产 ID 列表触发本地到 MinIO 迁移的请求体。
 */
export type DouyinMediaMigrationRequest = {
    asset_ids?: Array<(string)>;
};

/**
 * 触发任务媒体处理（下载与可选字幕转写）的请求体。
 */
export type DouyinMediaProcessRequest = {
    media_storage?: (MediaStorageBackend | null);
    translate_subtitles?: boolean;
    subtitle_only?: boolean;
    force_retranslate?: boolean;
    transcription_language?: string;
    cookies?: (string | null);
};

/**
 * 媒体下载/字幕失败重试请求体。
 */
export type DouyinMediaRetryRequest = {
    asset_ids?: Array<(string)>;
    retry_downloads?: boolean;
    retry_subtitles?: boolean;
    force_retranslate?: boolean;
};

/**
 * 任务媒体处理概览：下载、字幕与迁移各状态的数量统计。
 */
export type DouyinMediaSummaryPublic = {
    total: number;
    queued: number;
    downloading: number;
    downloaded: number;
    temporary: number;
    download_failed: number;
    subtitle_pending: number;
    subtitle_running: number;
    subtitle_completed: number;
    subtitle_failed: number;
    local_downloaded: number;
    minio_downloaded: number;
    migration_queued: number;
    migration_running: number;
    migration_cleanup_pending: number;
    migration_completed: number;
    migration_failed: number;
};

/**
 * 媒体任务管理读模型：以来源采集任务为依赖边界聚合下载与字幕状态。
 */
export type DouyinMediaTaskPublic = {
    source_task_id: string;
    track_id: string;
    track_name: string;
    track_is_default: boolean;
    source_title: (string | null);
    source_author: (string | null);
    source_creator_names?: Array<(string)>;
    crawl_type: string;
    crawl_status: string;
    checkpoint_phase: string;
    source_request?: {
        [key: string]: unknown;
    };
    eligible_count: number;
    dependency_ready: boolean;
    dependency_message: string;
    status: DouyinMediaTaskStatus;
    summary: DouyinMediaSummaryPublic;
    created_at: string;
    finished_at: (string | null);
};

/**
 * 媒体任务管理页分页响应。
 */
export type DouyinMediaTasksPublic = {
    data: Array<DouyinMediaTaskPublic>;
    count: number;
};

/**
 * 媒体处理任务在管理页中的聚合状态。
 */
export type DouyinMediaTaskStatus = 'waiting_source' | 'ready' | 'queued' | 'running' | 'attention' | 'completed';

/**
 * 请求延迟档位，决定请求间隔随机区间的基准范围。
 */
export type DouyinRequestDelayLevel = 'fast' | 'steady' | 'ultra_steady';

/**
 * 单条抖音请求日志的对外模型（响应体永不落库）。
 */
export type DouyinRequestLogPublic = {
    id: string;
    task_id: (string | null);
    method: string;
    path: string;
    url: string;
    query_params: {
        [key: string]: unknown;
    };
    request_headers: {
        [key: string]: unknown;
    };
    request_body: ({
    [key: string]: unknown;
} | null);
    response_status: (number | null);
    duration_ms: number;
    error: (string | null);
    failure_detail: ({
    [key: string]: unknown;
} | null);
    created_at: string;
};

/**
 * 抖音请求日志分页列表的对外模型。
 */
export type DouyinRequestLogsPublic = {
    data: Array<DouyinRequestLogPublic>;
    count: number;
};

/**
 * 按赛道返回的关键词/作者筛选项。
 */
export type DouyinSourceOptionPublic = {
    id: string;
    source_type: DouyinSourceType;
    name: string;
    usage_count: number;
};

/**
 * 关键词/作者来源筛选项列表。
 */
export type DouyinSourceOptionsPublic = {
    data: Array<DouyinSourceOptionPublic>;
    count: number;
};

/**
 * 任务与内容的来源类型。
 */
export type DouyinSourceType = 'keyword' | 'creator' | 'mixed' | 'task';

/**
 * 字幕导出格式。
 */
export type DouyinSubtitleExportFormat = 'txt' | 'srt' | 'vtt';

/**
 * 字幕批量导出请求体。
 */
export type DouyinSubtitleExportRequest = {
    aweme_ids: Array<(string)>;
    format?: DouyinSubtitleExportFormat;
};

/**
 * 字幕记录的对外只读视图（segments 已解析为对象列表）。
 */
export type DouyinSubtitlePublic = {
    id: string;
    asset_id: string;
    task_id: string;
    aweme_id: string;
    status: SubtitleStatus;
    progress: number;
    attempt_count: number;
    requested_backend: string;
    actual_backend: string;
    model: string;
    language: string;
    duration_seconds: number;
    full_text: string;
    segments: Array<{
        [key: string]: unknown;
    }>;
    error: (string | null);
    created_at: string;
    started_at: (string | null);
    finished_at: (string | null);
};

/**
 * 标签详情响应模型：在引用基础上附带关联统计。
 */
export type DouyinTagPublic = {
    id: string;
    name: string;
    aweme_count: number;
    task_count: number;
    last_seen_at: string;
    created_at: string;
};

/**
 * 标签引用模型：仅含 id 与名称，用于嵌套展示。
 */
export type DouyinTagRefPublic = {
    id: string;
    name: string;
};

/**
 * 标签分页列表响应。
 */
export type DouyinTagsPublic = {
    data: Array<DouyinTagPublic>;
    count: number;
};

/**
 * 标签历史同步结果统计。
 */
export type DouyinTagSyncResult = {
    aweme_count: number;
    tag_count: number;
    created_count: number;
    binding_count: number;
};

/**
 * 创建赛道的请求模型。
 */
export type DouyinTrackCreate = {
    name: string;
    description?: string;
    prompt?: string;
    keywords?: Array<(string)>;
    default_task_config?: DouyinTrackTaskDefaults;
    reply_templates?: Array<(string)>;
    keyword_categories?: Array<(string)>;
};

/**
 * 向赛道批量追加达人的请求模型。
 */
export type DouyinTrackCreatorAdd = {
    creators: Array<(string)>;
};

/**
 * 赛道详情的对外模型，额外包含分析提示词。
 */
export type DouyinTrackDetailPublic = {
    id: string;
    name: string;
    description: string;
    enabled: boolean;
    is_default: boolean;
    default_task_config: DouyinTrackTaskDefaults;
    keyword_count: number;
    enabled_keyword_count: number;
    task_count: number;
    active_task_count: number;
    aweme_count: number;
    comment_count: number;
    last_task_id: (string | null);
    last_task_status: (CrawlTaskStatus | null);
    last_run_at: (string | null);
    created_at: string;
    updated_at: string;
    prompt: string;
    reply_templates: Array<(string)>;
    keyword_categories: Array<(string)>;
};

/**
 * 向赛道批量追加关键词的请求模型。
 */
export type DouyinTrackKeywordAdd = {
    keywords: Array<(string)>;
};

/**
 * 赛道概要（含聚合统计）的对外模型。
 */
export type DouyinTrackPublic = {
    id: string;
    name: string;
    description: string;
    enabled: boolean;
    is_default: boolean;
    default_task_config: DouyinTrackTaskDefaults;
    keyword_count: number;
    enabled_keyword_count: number;
    task_count: number;
    active_task_count: number;
    aweme_count: number;
    comment_count: number;
    last_task_id: (string | null);
    last_task_status: (CrawlTaskStatus | null);
    last_run_at: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * 赛道分页列表的对外模型。
 */
export type DouyinTracksPublic = {
    data: Array<DouyinTrackPublic>;
    count: number;
};

/**
 * 赛道级默认爬取参数，与通用任务的风险控制和媒体参数保持一致。
 */
export type DouyinTrackTaskDefaults = {
    mode?: DouyinKeywordBatchMode;
    start_page?: number;
    max_awemes?: number;
    fetch_comments?: boolean;
    fetch_sub_comments?: boolean;
    max_comments_per_aweme?: number;
    concurrency?: number;
    request_delay_level?: DouyinRequestDelayLevel;
    request_interval_seconds?: number;
    task_interval_seconds?: (number | null);
    publish_time?: number;
    browser_mode?: (DouyinBrowserMode | null);
    media_processing_mode?: MediaProcessingMode;
    media_storage?: (MediaStorageBackend | null);
    download_media?: boolean;
    translate_subtitles?: boolean;
    transcription_language?: string;
    account_id?: (string | null);
    account_ids?: Array<(string)>;
    account_pool_id?: (string | null);
    account_strategy?: DouyinAccountPoolStrategy;
};

/**
 * 基于赛道关键词批量创建采集任务的请求模型。
 */
export type DouyinTrackTaskRequest = {
    mode?: DouyinKeywordBatchMode;
    start_page?: number;
    max_awemes?: number;
    fetch_comments?: boolean;
    fetch_sub_comments?: boolean;
    max_comments_per_aweme?: number;
    concurrency?: number;
    request_delay_level?: DouyinRequestDelayLevel;
    request_interval_seconds?: number;
    task_interval_seconds?: (number | null);
    publish_time?: number;
    browser_mode?: (DouyinBrowserMode | null);
    media_processing_mode?: MediaProcessingMode;
    media_storage?: (MediaStorageBackend | null);
    download_media?: boolean;
    translate_subtitles?: boolean;
    transcription_language?: string;
    account_id?: (string | null);
    account_ids?: Array<(string)>;
    account_pool_id?: (string | null);
    account_strategy?: DouyinAccountPoolStrategy;
    login_type?: DouyinLoginType;
    cookies?: (string | null);
    /**
     * 本次运行选中的赛道关键词 ID；省略或传空数组且未指定达人时，运行该赛道全部已启用关键词
     */
    keyword_ids?: Array<(string)>;
    /**
     * 本次运行选中的赛道达人 ID；省略或传空数组时只运行关键词
     */
    creator_ids?: Array<(string)>;
};

/**
 * 更新赛道的请求模型，各字段均为可选部分更新。
 */
export type DouyinTrackUpdate = {
    name?: (string | null);
    description?: (string | null);
    prompt?: (string | null);
    enabled?: (boolean | null);
    default_task_config?: (DouyinTrackTaskDefaults | null);
    reply_templates?: (Array<(string)> | null);
    keyword_categories?: (Array<(string)> | null);
};

/**
 * 用户行为对外响应模型。
 */
export type DouyinUserActionPublic = {
    id: string;
    task_id: string;
    account_hash: string;
    aweme_id: string;
    action_type: string;
    observed_at: string;
};

/**
 * 用户行为分页列表响应。
 */
export type DouyinUserActionsPublic = {
    data: Array<DouyinUserActionPublic>;
    count: number;
};

/**
 * 作品库单个作品的对外展示模型，聚合作品元数据与其关联资源。
 */
export type DouyinWorkPublic = {
    aweme: DouyinAwemePublic;
    persisted_comment_count: number;
    media: (DouyinMediaAssetPublic | null);
    tags?: Array<DouyinTagRefPublic>;
};

/**
 * 作品库分页列表响应模型。
 */
export type DouyinWorksPublic = {
    data: Array<DouyinWorkPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * 集成文档总览模型：汇总 HTTP API 与 MCP 服务的接入信息。
 */
export type IntegrationDocsPublic = {
    api_title: string;
    api_version: string;
    api_openapi_url: string;
    api_swagger_url: string;
    api_operations: Array<ApiOperationDocPublic>;
    api_operation_count: number;
    mcp_server_name: string;
    mcp_streamable_http_url: string;
    mcp_health_url: string;
    mcp_stdio_command: string;
    mcp_http_command: string;
    mcp_tools: Array<McpToolDocPublic>;
    mcp_tool_count: number;
};

/**
 * 创建 Item 的入参模型。
 */
export type ItemCreate = {
    title: string;
    description?: (string | null);
};

/**
 * 对外返回的单条 Item 视图模型。
 */
export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

/**
 * 对外返回的 Item 分页列表模型。
 */
export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

/**
 * 更新 Item 的入参模型，字段均可选。
 */
export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * 单个 MCP 工具的文档视图模型。
 */
export type McpToolDocPublic = {
    name: string;
    title: (string | null);
    description: string;
    input_schema: {
        [key: string]: unknown;
    };
    output_schema: ({
    [key: string]: unknown;
} | null);
};

/**
 * 媒体资产下载状态机。
 */
export type MediaDownloadStatus = 'queued' | 'downloading' | 'downloaded' | 'temporary' | 'failed';

/**
 * 本地到 MinIO 的单向迁移状态机。
 */
export type MediaMigrationStatus = 'idle' | 'queued' | 'uploading' | 'verifying' | 'switching' | 'cleanup_pending' | 'completed' | 'failed';

/**
 * 媒体处理模式：控制采集任务中媒体下载/字幕处理的触发方式。
 */
export type MediaProcessingMode = 'none' | 'immediate' | 'batch';

/**
 * 媒体存储后端。
 */
export type MediaStorageBackend = 'local' | 'minio';

/**
 * 通用消息响应模型，用于仅需返回一段提示文本的接口。
 */
export type Message = {
    message: string;
};

/**
 * 通过重置令牌设置新密码的入参模型。
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * 私有接口创建用户的请求模型。
 */
export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * 字幕转写状态机。
 */
export type SubtitleStatus = 'pending' | 'running' | 'completed' | 'failed';

/**
 * 登录成功后返回的访问令牌模型。
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * 修改密码入参模型。
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * 管理员创建用户时的入参模型。
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * 对外返回的单用户视图模型（不含敏感字段）。
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * 用户自助注册时的入参模型。
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * 对外返回的用户分页列表模型。
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * 管理员更新用户时的入参模型，所有字段均可选。
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * 当前登录用户更新自身资料时的入参模型。
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DouyinCreateTaskData = {
    requestBody: CrawlTaskCreate;
};

export type DouyinCreateTaskResponse = (CrawlTaskPublic);

export type DouyinListTasksData = {
    limit?: number;
    skip?: number;
    sourceId?: (string | null);
    sourceType?: (DouyinSourceType | null);
    trackId?: (string | null);
};

export type DouyinListTasksResponse = (CrawlTasksPublic);

export type DouyinListCommentLibraryData = {
    awemeId?: (string | null);
    commentContent?: (string | null);
    commentType?: 'all' | 'top_level' | 'reply';
    hasPictures?: 'all' | 'yes' | 'no';
    limit?: number;
    maxLikes?: (number | null);
    minLikes?: (number | null);
    publishedFrom?: (number | null);
    publishedTo?: (number | null);
    search?: (string | null);
    skip?: number;
    sortBy?: 'published_at' | 'like_count' | 'sub_comment_count' | 'fetched_at';
    sortOrder?: 'asc' | 'desc';
    sourceId?: (string | null);
    sourceKeyword?: (string | null);
    sourceType?: (DouyinSourceType | null);
    taskId?: (string | null);
    trackId?: (string | null);
    videoCreator?: (string | null);
};

export type DouyinListCommentLibraryResponse = (DouyinCommentLibraryPublic);

export type DouyinExportCommentSelectionData = {
    requestBody: DouyinCommentSelectionExportRequest;
};

export type DouyinExportCommentSelectionResponse = (unknown);

export type DouyinListLibraryCreatorsData = {
    taskId?: (string | null);
    trackId?: (string | null);
};

export type DouyinListLibraryCreatorsResponse = (DouyinCreatorOptionsPublic);

export type DouyinListSourceOptionsData = {
    trackId: string;
};

export type DouyinListSourceOptionsResponse = (DouyinSourceOptionsPublic);

export type DouyinListLibraryWorksData = {
    creatorHash?: (string | null);
    downloadStatus?: 'all' | 'missing' | 'queued' | 'downloading' | 'downloaded' | 'failed';
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: 'published_at' | 'liked_count' | 'comment_count' | 'collected_count' | 'persisted_comment_count' | 'downloaded_at' | 'file_size' | 'fetched_at';
    sortOrder?: 'asc' | 'desc';
    sourceId?: (string | null);
    sourceType?: (DouyinSourceType | null);
    storageBackend?: 'all' | 'local' | 'minio';
    subtitleStatus?: 'all' | 'pending' | 'running' | 'completed' | 'failed';
    tagId?: (string | null);
    taskId?: (string | null);
    trackId?: (string | null);
};

export type DouyinListLibraryWorksResponse = (DouyinWorksPublic);

export type DouyinMigrateLibraryMediaToMinioData = {
    requestBody: DouyinLibraryMediaMigrationRequest;
};

export type DouyinMigrateLibraryMediaToMinioResponse = (DouyinMediaMigrationAccepted);

export type DouyinGetTaskData = {
    taskId: string;
};

export type DouyinGetTaskResponse = (CrawlTaskPublic);

export type DouyinDeleteTaskData = {
    taskId: string;
};

export type DouyinDeleteTaskResponse = (Message);

export type DouyinBulkDeleteTasksData = {
    requestBody: CrawlTaskBulkDeleteRequest;
};

export type DouyinBulkDeleteTasksResponse = (Message);

export type DouyinBulkResumeTasksData = {
    requestBody: CrawlTaskBulkResumeRequest;
};

export type DouyinBulkResumeTasksResponse = (CrawlTaskBulkResumePublic);

export type DouyinListTaskShardsData = {
    taskId: string;
};

export type DouyinListTaskShardsResponse = (CrawlTaskShardsPublic);

export type DouyinCancelTaskData = {
    taskId: string;
};

export type DouyinCancelTaskResponse = (Message);

export type DouyinResumeTaskData = {
    requestBody: CrawlTaskResumeRequest;
    taskId: string;
};

export type DouyinResumeTaskResponse = (CrawlTaskPublic);

export type DouyinRestartTaskData = {
    taskId: string;
};

export type DouyinRestartTaskResponse = (CrawlTaskPublic);

export type DouyinListMediaTasksData = {
    limit?: number;
    skip?: number;
    trackId?: (string | null);
};

export type DouyinListMediaTasksResponse = (DouyinMediaTasksPublic);

export type DouyinListMediaData = {
    limit?: number;
    skip?: number;
    taskId: string;
};

export type DouyinListMediaResponse = (DouyinMediaAssetsPublic);

export type DouyinGetMediaSummaryData = {
    taskId: string;
};

export type DouyinGetMediaSummaryResponse = (DouyinMediaSummaryPublic);

export type DouyinMigrateMediaToMinioData = {
    requestBody: DouyinMediaMigrationRequest;
    taskId: string;
};

export type DouyinMigrateMediaToMinioResponse = (DouyinMediaMigrationAccepted);

export type DouyinProcessMediaData = {
    requestBody: DouyinMediaProcessRequest;
    taskId: string;
};

export type DouyinProcessMediaResponse = (CrawlTaskPublic);

export type DouyinRetryMediaData = {
    requestBody: DouyinMediaRetryRequest;
    taskId: string;
};

export type DouyinRetryMediaResponse = (Message);

export type DouyinRetranslateMediaData = {
    assetId: string;
    taskId: string;
};

export type DouyinRetranslateMediaResponse = (Message);

export type DouyinDownloadMediaFileData = {
    assetId: string;
    taskId: string;
};

export type DouyinDownloadMediaFileResponse = (unknown);

export type DouyinCreateMediaPreviewSessionData = {
    assetId: string;
    taskId: string;
};

export type DouyinCreateMediaPreviewSessionResponse = (Message);

export type DouyinPreviewMediaFileData = {
    assetId: string;
    douyinMediaPreview?: (string | null);
    range?: (string | null);
    taskId: string;
};

export type DouyinPreviewMediaFileResponse = (unknown);

export type DouyinGetQrcodeData = {
    taskId: string;
};

export type DouyinGetQrcodeResponse = (unknown);

export type DouyinListWorksData = {
    downloadStatus?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: 'published_at' | 'liked_count' | 'comment_count' | 'collected_count' | 'persisted_comment_count' | 'fetched_at';
    sortOrder?: 'asc' | 'desc';
    storageBackend?: (string | null);
    subtitleStatus?: (string | null);
    tagId?: (string | null);
    taskId: string;
};

export type DouyinListWorksResponse = (DouyinWorksPublic);

export type DouyinGetWorkData = {
    awemeId: string;
    taskId: string;
};

export type DouyinGetWorkResponse = (DouyinWorkPublic);

export type DouyinListAwemesData = {
    limit?: number;
    skip?: number;
    sortBy?: 'published_at' | 'liked_count' | 'comment_count' | 'collected_count' | 'fetched_at';
    sortOrder?: 'asc' | 'desc';
    taskId: string;
};

export type DouyinListAwemesResponse = (DouyinAwemesPublic);

export type DouyinRecrawlAwemeCommentsData = {
    awemeId: string;
    requestBody: DouyinAwemeCommentCrawlRequest;
    taskId: string;
};

export type DouyinRecrawlAwemeCommentsResponse = (CrawlTaskPublic);

export type DouyinCrawlAwemeCreatorData = {
    awemeId: string;
    requestBody: DouyinAwemeCreatorCrawlRequest;
    taskId: string;
};

export type DouyinCrawlAwemeCreatorResponse = (CrawlTaskPublic);

export type DouyinListCommentsData = {
    awemeId?: (string | null);
    limit?: number;
    skip?: number;
    sortBy?: 'published_at' | 'like_count' | 'fetched_at';
    sortOrder?: 'asc' | 'desc';
    taskId: string;
};

export type DouyinListCommentsResponse = (DouyinCommentsPublic);

export type DouyinExportCommentsData = {
    requestBody: DouyinCommentExportRequest;
    taskId: string;
};

export type DouyinExportCommentsResponse = (unknown);

export type DouyinExportSubtitlesData = {
    requestBody: DouyinSubtitleExportRequest;
    taskId: string;
};

export type DouyinExportSubtitlesResponse = (unknown);

export type DouyinListActionsData = {
    limit?: number;
    skip?: number;
    taskId: string;
};

export type DouyinListActionsResponse = (DouyinUserActionsPublic);

export type DouyinListRequestLogsData = {
    createdFrom?: (string | null);
    createdTo?: (string | null);
    limit?: number;
    method?: (string | null);
    path?: (string | null);
    responseStatus?: (number | null);
    skip?: number;
    taskId?: (string | null);
};

export type DouyinListRequestLogsResponse = (DouyinRequestLogsPublic);

export type DouyinAccountsListAccountsData = {
    limit?: number;
    skip?: number;
};

export type DouyinAccountsListAccountsResponse = (DouyinAccountsPublic);

export type DouyinAccountsAddAccountData = {
    requestBody: DouyinAccountCreate;
};

export type DouyinAccountsAddAccountResponse = (DouyinAccountPublic);

export type DouyinAccountsListBrowserSlotsResponse = (DouyinBrowserSlotsPublic);

export type DouyinAccountsEditAccountData = {
    accountId: string;
    requestBody: DouyinAccountUpdate;
};

export type DouyinAccountsEditAccountResponse = (DouyinAccountPublic);

export type DouyinAccountsDeleteAccountData = {
    accountId: string;
};

export type DouyinAccountsDeleteAccountResponse = (Message);

export type DouyinAccountsStartAccountLoginData = {
    accountId: string;
};

export type DouyinAccountsStartAccountLoginResponse = (DouyinAccountLoginSessionPublic);

export type DouyinAccountsVerifyAccountLoginData = {
    accountId: string;
};

export type DouyinAccountsVerifyAccountLoginResponse = (DouyinAccountPublic);

export type DouyinAccountsListPoolsResponse = (DouyinAccountPoolsPublic);

export type DouyinAccountsAddPoolData = {
    requestBody: DouyinAccountPoolCreate;
};

export type DouyinAccountsAddPoolResponse = (DouyinAccountPoolPublic);

export type DouyinAccountsEditPoolData = {
    poolId: string;
    requestBody: DouyinAccountPoolUpdate;
};

export type DouyinAccountsEditPoolResponse = (DouyinAccountPoolPublic);

export type DouyinAccountsDeletePoolData = {
    poolId: string;
};

export type DouyinAccountsDeletePoolResponse = (Message);

export type DouyinCreatorsListCreatorsData = {
    enabled?: (boolean | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: 'nickname' | 'status' | 'task_count' | 'aweme_count' | 'last_crawled_at' | 'created_at';
    sortOrder?: 'asc' | 'desc';
    status?: (DouyinCreatorStatus | null);
    trackId?: (string | null);
};

export type DouyinCreatorsListCreatorsResponse = (DouyinCreatorsPublic);

export type DouyinCreatorsBulkCreateCreatorsData = {
    requestBody: DouyinCreatorBulkCreateRequest;
};

export type DouyinCreatorsBulkCreateCreatorsResponse = (DouyinCreatorBulkCreateResult);

export type DouyinCreatorsEditCreatorData = {
    creatorId: string;
    requestBody: DouyinCreatorUpdate;
};

export type DouyinCreatorsEditCreatorResponse = (DouyinCreatorPublic);

export type DouyinCreatorsDeleteCreatorData = {
    creatorId: string;
};

export type DouyinCreatorsDeleteCreatorResponse = (Message);

export type DouyinCreatorsBulkDeleteCreatorsData = {
    requestBody: DouyinBulkDeleteRequest;
};

export type DouyinCreatorsBulkDeleteCreatorsResponse = (Message);

export type DouyinCreatorsListCreatorTasksData = {
    creatorId: string;
};

export type DouyinCreatorsListCreatorTasksResponse = (Array<CrawlTaskPublic>);

export type DouyinCreatorsSyncCreatorsFromTaskData = {
    taskId: string;
};

export type DouyinCreatorsSyncCreatorsFromTaskResponse = (DouyinCreatorSyncResult);

export type DouyinCreatorsSyncHistoricalCreatorsResponse = (DouyinCreatorSyncResult);

export type DouyinCreatorsSyncCreatorsFromAwemesResponse = (DouyinAwemeSyncResult);

export type DouyinCreatorsCreateCreatorTasksData = {
    requestBody: DouyinCreatorBatchTaskRequest;
};

export type DouyinCreatorsCreateCreatorTasksResponse = (DouyinCreatorTaskBatchResult);

export type DouyinInteractionsPreflightInteractionData = {
    requestBody: DouyinInteractionCreate;
};

export type DouyinInteractionsPreflightInteractionResponse = (DouyinInteractionPreflightPublic);

export type DouyinInteractionsPrepareInteractionData = {
    requestBody: DouyinInteractionCreate;
};

export type DouyinInteractionsPrepareInteractionResponse = (DouyinInteractionPublic);

export type DouyinInteractionsListInteractionsData = {
    awemeId?: (string | null);
    interactionType?: (DouyinInteractionType | null);
    limit?: number;
    skip?: number;
    sourceId?: (string | null);
    sourceType?: (DouyinSourceType | null);
    status?: (DouyinInteractionStatus | null);
    taskId?: (string | null);
    trackId?: (string | null);
};

export type DouyinInteractionsListInteractionsResponse = (DouyinInteractionsPublic);

export type DouyinInteractionsCreateBatchCommentsData = {
    requestBody: DouyinBatchCommentCreate;
};

export type DouyinInteractionsCreateBatchCommentsResponse = (DouyinBatchCommentPublic);

export type DouyinInteractionsListInteractionQuotaResponse = (Array<DouyinInteractionQuotaPublic>);

export type DouyinInteractionsGetInteractionData = {
    interactionId: string;
};

export type DouyinInteractionsGetInteractionResponse = (DouyinInteractionDetailPublic);

export type DouyinInteractionsGetInteractionEventScreenshotData = {
    eventId: string;
    interactionId: string;
};

export type DouyinInteractionsGetInteractionEventScreenshotResponse = (unknown);

export type DouyinInteractionsConfirmInteractionData = {
    interactionId: string;
};

export type DouyinInteractionsConfirmInteractionResponse = (DouyinInteractionPublic);

export type DouyinInteractionsRetryInteractionData = {
    interactionId: string;
    requestBody: DouyinInteractionRetryRequest;
};

export type DouyinInteractionsRetryInteractionResponse = (DouyinInteractionPublic);

export type DouyinInteractionsCancelInteractionData = {
    interactionId: string;
};

export type DouyinInteractionsCancelInteractionResponse = (DouyinInteractionPublic);

export type DouyinKeywordsListKeywordsData = {
    category?: (string | null);
    enabled?: (boolean | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: 'keyword' | 'status' | 'task_count' | 'aweme_count' | 'last_crawled_at' | 'created_at';
    sortOrder?: 'asc' | 'desc';
    status?: (DouyinKeywordStatus | null);
    trackId?: (string | null);
};

export type DouyinKeywordsListKeywordsResponse = (DouyinKeywordsPublic);

export type DouyinKeywordsBulkCreateKeywordsData = {
    requestBody: DouyinKeywordBulkCreateRequest;
};

export type DouyinKeywordsBulkCreateKeywordsResponse = (DouyinKeywordBulkCreateResult);

export type DouyinKeywordsEditKeywordData = {
    keywordId: string;
    requestBody: DouyinKeywordUpdate;
};

export type DouyinKeywordsEditKeywordResponse = (DouyinKeywordPublic);

export type DouyinKeywordsDeleteKeywordData = {
    keywordId: string;
};

export type DouyinKeywordsDeleteKeywordResponse = (Message);

export type DouyinKeywordsBulkDeleteKeywordsData = {
    requestBody: DouyinBulkDeleteRequest;
};

export type DouyinKeywordsBulkDeleteKeywordsResponse = (Message);

export type DouyinKeywordsListKeywordTasksData = {
    keywordId: string;
};

export type DouyinKeywordsListKeywordTasksResponse = (Array<CrawlTaskPublic>);

export type DouyinKeywordsSyncKeywordsFromTaskData = {
    taskId: string;
};

export type DouyinKeywordsSyncKeywordsFromTaskResponse = (DouyinKeywordSyncResult);

export type DouyinKeywordsSyncHistoricalKeywordsResponse = (DouyinKeywordSyncResult);

export type DouyinKeywordsCreateKeywordTasksData = {
    requestBody: DouyinKeywordBatchTaskRequest;
};

export type DouyinKeywordsCreateKeywordTasksResponse = (DouyinKeywordTaskBatchResult);

export type DouyinTagsListTagsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: 'name' | 'aweme_count' | 'task_count' | 'last_seen_at';
    sortOrder?: 'asc' | 'desc';
    taskId?: (string | null);
    trackId?: (string | null);
};

export type DouyinTagsListTagsResponse = (DouyinTagsPublic);

export type DouyinTagsSyncTagsResponse = (DouyinTagSyncResult);

export type DouyinTracksListTracksData = {
    enabled?: (boolean | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type DouyinTracksListTracksResponse = (DouyinTracksPublic);

export type DouyinTracksAddTrackData = {
    requestBody: DouyinTrackCreate;
};

export type DouyinTracksAddTrackResponse = (DouyinTrackDetailPublic);

export type DouyinTracksGetTrackData = {
    trackId: string;
};

export type DouyinTracksGetTrackResponse = (DouyinTrackDetailPublic);

export type DouyinTracksEditTrackData = {
    requestBody: DouyinTrackUpdate;
    trackId: string;
};

export type DouyinTracksEditTrackResponse = (DouyinTrackDetailPublic);

export type DouyinTracksDeleteTrackData = {
    trackId: string;
};

export type DouyinTracksDeleteTrackResponse = (Message);

export type DouyinTracksBulkDeleteTracksData = {
    requestBody: DouyinBulkDeleteRequest;
};

export type DouyinTracksBulkDeleteTracksResponse = (Message);

export type DouyinTracksListTrackKeywordsData = {
    trackId: string;
};

export type DouyinTracksListTrackKeywordsResponse = (DouyinKeywordsPublic);

export type DouyinTracksAppendTrackKeywordsData = {
    requestBody: DouyinTrackKeywordAdd;
    trackId: string;
};

export type DouyinTracksAppendTrackKeywordsResponse = (DouyinKeywordsPublic);

export type DouyinTracksRemoveTrackKeywordData = {
    keywordId: string;
    trackId: string;
};

export type DouyinTracksRemoveTrackKeywordResponse = (Message);

export type DouyinTracksListTrackCreatorsData = {
    trackId: string;
};

export type DouyinTracksListTrackCreatorsResponse = (DouyinCreatorsPublic);

export type DouyinTracksAppendTrackCreatorsData = {
    requestBody: DouyinTrackCreatorAdd;
    trackId: string;
};

export type DouyinTracksAppendTrackCreatorsResponse = (DouyinCreatorsPublic);

export type DouyinTracksRemoveTrackCreatorData = {
    creatorId: string;
    trackId: string;
};

export type DouyinTracksRemoveTrackCreatorResponse = (Message);

export type DouyinTracksCreateTrackTasksData = {
    requestBody: DouyinTrackTaskRequest;
    trackId: string;
};

export type DouyinTracksCreateTrackTasksResponse = (DouyinKeywordTaskBatchResult);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SystemIntegrationsGetIntegrationDocsResponse = (IntegrationDocsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);