// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CrawlTaskCreate = {
    crawl_type?: DouyinCrawlType;
    login_type?: DouyinLoginType;
    cookies?: (string | null);
    keywords?: Array<(string)>;
    video_ids?: Array<(string)>;
    creator_ids?: Array<(string)>;
    start_page?: number;
    max_awemes?: number;
    fetch_comments?: boolean;
    fetch_sub_comments?: boolean;
    max_comments_per_aweme?: number;
    concurrency?: number;
    request_interval_seconds?: number;
    publish_time?: number;
};

export type CrawlTaskPublic = {
    id: string;
    owner_id: string;
    crawl_type: DouyinCrawlType;
    status: CrawlTaskStatus;
    request: {
        [key: string]: unknown;
    };
    aweme_count: number;
    comment_count: number;
    action_count: number;
    error: (string | null);
    has_qrcode: boolean;
    created_at: string;
    started_at: (string | null);
    finished_at: (string | null);
};

export type CrawlTasksPublic = {
    data: Array<CrawlTaskPublic>;
    count: number;
};

export type CrawlTaskStatus = 'queued' | 'waiting_login' | 'running' | 'cancelling' | 'succeeded' | 'failed' | 'cancelled' | 'interrupted';

export type DouyinAwemePublic = {
    id: string;
    task_id: string;
    aweme_id: string;
    aweme_type: string;
    title: string;
    description: string;
    create_time: (number | null);
    creator_hash: string;
    sec_uid: string;
    nickname: string;
    liked_count: number;
    collected_count: number;
    comment_count: number;
    share_count: number;
    aweme_url: string;
    cover_url: string;
    video_download_url: string;
    music_download_url: string;
    note_download_url: string;
    source_keyword: string;
    fetched_at: string;
};

export type DouyinAwemesPublic = {
    data: Array<DouyinAwemePublic>;
    count: number;
};

export type DouyinCommentPublic = {
    id: string;
    task_id: string;
    comment_id: string;
    aweme_id: string;
    parent_comment_id: string;
    content: string;
    create_time: (number | null);
    creator_hash: string;
    sec_uid: string;
    nickname: string;
    sub_comment_count: number;
    like_count: number;
    pictures: string;
    fetched_at: string;
};

export type DouyinCommentsPublic = {
    data: Array<DouyinCommentPublic>;
    count: number;
};

export type DouyinCrawlType = 'search' | 'detail' | 'creator' | 'liked' | 'collected';

export type DouyinLoginType = 'qrcode' | 'cookie';

export type DouyinUserActionPublic = {
    id: string;
    task_id: string;
    account_hash: string;
    aweme_id: string;
    action_type: string;
    observed_at: string;
};

export type DouyinUserActionsPublic = {
    data: Array<DouyinUserActionPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DouyinCreateTaskData = {
    requestBody: CrawlTaskCreate;
};

export type DouyinCreateTaskResponse = (CrawlTaskPublic);

export type DouyinListTasksData = {
    limit?: number;
    skip?: number;
};

export type DouyinListTasksResponse = (CrawlTasksPublic);

export type DouyinGetTaskData = {
    taskId: string;
};

export type DouyinGetTaskResponse = (CrawlTaskPublic);

export type DouyinCancelTaskData = {
    taskId: string;
};

export type DouyinCancelTaskResponse = (Message);

export type DouyinGetQrcodeData = {
    taskId: string;
};

export type DouyinGetQrcodeResponse = (unknown);

export type DouyinListAwemesData = {
    limit?: number;
    skip?: number;
    taskId: string;
};

export type DouyinListAwemesResponse = (DouyinAwemesPublic);

export type DouyinListCommentsData = {
    awemeId?: (string | null);
    limit?: number;
    skip?: number;
    taskId: string;
};

export type DouyinListCommentsResponse = (DouyinCommentsPublic);

export type DouyinListActionsData = {
    limit?: number;
    skip?: number;
    taskId: string;
};

export type DouyinListActionsResponse = (DouyinUserActionsPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);