// This file is auto-generated by @hey-api/openapi-ts

export type ApiOperationDocPublic = {
    method: string;
    path: string;
    summary: string;
    description: string;
    operation_id: string;
    tags: Array<(string)>;
    auth_required: boolean;
    parameters: Array<{
        [key: string]: unknown;
    }>;
    request_body: ({
    [key: string]: unknown;
} | null);
    response_codes: Array<(string)>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CrawlTaskCreate = {
    crawl_type?: DouyinCrawlType;
    login_type?: DouyinLoginType;
    browser_mode?: (DouyinBrowserMode | null);
    cookies?: (string | null);
    keywords?: Array<(string)>;
    video_ids?: Array<(string)>;
    creator_ids?: Array<(string)>;
    start_page?: number;
    max_awemes?: number;
    fetch_comments?: boolean;
    fetch_sub_comments?: boolean;
    max_comments_per_aweme?: number;
    concurrency?: number;
    request_delay_level?: DouyinRequestDelayLevel;
    request_interval_seconds?: number;
    publish_time?: number;
    media_processing_mode?: MediaProcessingMode;
    media_storage?: (MediaStorageBackend | null);
    download_media?: boolean;
    translate_subtitles?: boolean;
    transcription_language?: string;
    account_id?: (string | null);
    account_ids?: Array<(string)>;
    account_pool_id?: (string | null);
    account_strategy?: DouyinAccountPoolStrategy;
};

export type CrawlTaskPhase = 'crawl' | 'media' | 'completed';

export type CrawlTaskPublic = {
    id: string;
    owner_id: string;
    account_id: (string | null);
    account_pool_id: (string | null);
    account_strategy: DouyinAccountPoolStrategy;
    crawl_type: DouyinCrawlType;
    status: CrawlTaskStatus;
    request: {
        [key: string]: unknown;
    };
    aweme_count: number;
    comment_count: number;
    action_count: number;
    checkpoint_phase: CrawlTaskPhase;
    resume_count: number;
    can_resume_crawl: boolean;
    can_resume_media: boolean;
    error: (string | null);
    has_qrcode: boolean;
    created_at: string;
    started_at: (string | null);
    finished_at: (string | null);
    last_resumed_at: (string | null);
};

export type CrawlTaskResumeRequest = {
    resume_crawl?: (boolean | null);
    resume_media?: (boolean | null);
    cookies?: (string | null);
};

export type CrawlTaskShardPublic = {
    id: string;
    task_id: string;
    account_id: (string | null);
    account_name: (string | null);
    shard_index: number;
    status: CrawlTaskShardStatus;
    request: {
        [key: string]: unknown;
    };
    aweme_count: number;
    comment_count: number;
    error: (string | null);
    started_at: (string | null);
    finished_at: (string | null);
    created_at: string;
};

export type CrawlTaskShardsPublic = {
    data: Array<CrawlTaskShardPublic>;
    count: number;
};

export type CrawlTaskShardStatus = 'queued' | 'running' | 'succeeded' | 'failed' | 'interrupted' | 'cancelled';

export type CrawlTasksPublic = {
    data: Array<CrawlTaskPublic>;
    count: number;
};

export type CrawlTaskStatus = 'queued' | 'waiting_login' | 'running' | 'processing_media' | 'cancelling' | 'succeeded' | 'failed' | 'cancelled' | 'interrupted';

export type DouyinAccountCreate = {
    name: string;
    browser_mode?: DouyinBrowserMode;
    remote_slot?: (string | null);
    weight?: number;
    priority?: number;
    concurrency_limit?: number;
    daily_task_limit?: number;
    min_request_interval_seconds?: number;
};

export type DouyinAccountLoginSessionPublic = {
    account: DouyinAccountPublic;
    status: DouyinAccountStatus;
    browser_mode: DouyinBrowserMode;
    viewer_url: (string | null);
    expires_at: string;
    message: string;
};

export type DouyinAccountPoolCreate = {
    name: string;
    description?: string;
    strategy?: DouyinAccountPoolStrategy;
    max_parallel_accounts?: number;
    account_ids?: Array<(string)>;
};

export type DouyinAccountPoolPublic = {
    id: string;
    name: string;
    description: string;
    strategy: DouyinAccountPoolStrategy;
    max_parallel_accounts: number;
    enabled: boolean;
    accounts: Array<DouyinAccountPublic>;
    created_at: string;
    updated_at: string;
};

export type DouyinAccountPoolsPublic = {
    data: Array<DouyinAccountPoolPublic>;
    count: number;
};

export type DouyinAccountPoolStrategy = 'least_loaded' | 'round_robin' | 'weighted_round_robin';

export type DouyinAccountPoolUpdate = {
    name?: (string | null);
    description?: (string | null);
    strategy?: (DouyinAccountPoolStrategy | null);
    max_parallel_accounts?: (number | null);
    account_ids?: (Array<(string)> | null);
    enabled?: (boolean | null);
};

export type DouyinAccountPublic = {
    id: string;
    name: string;
    browser_mode: DouyinBrowserMode;
    remote_slot: (string | null);
    status: DouyinAccountStatus;
    is_logged_in: boolean;
    weight: number;
    priority: number;
    concurrency_limit: number;
    daily_task_limit: number;
    tasks_today: number;
    min_request_interval_seconds: number;
    active_leases: number;
    failure_streak: number;
    cooldown_until: (string | null);
    last_verified_at: (string | null);
    last_used_at: (string | null);
    last_error: (string | null);
    enabled: boolean;
    created_at: string;
    updated_at: string;
};

export type DouyinAccountsPublic = {
    data: Array<DouyinAccountPublic>;
    count: number;
};

export type DouyinAccountStatus = 'login_required' | 'verifying' | 'ready' | 'busy' | 'cooldown' | 'unhealthy' | 'disabled';

export type DouyinAccountUpdate = {
    name?: (string | null);
    remote_slot?: (string | null);
    weight?: (number | null);
    priority?: (number | null);
    concurrency_limit?: (number | null);
    daily_task_limit?: (number | null);
    min_request_interval_seconds?: (number | null);
    enabled?: (boolean | null);
};

export type DouyinAwemeCommentCrawlRequest = {
    browser_mode?: (DouyinBrowserMode | null);
    cookies?: (string | null);
    fetch_sub_comments?: boolean;
    max_comments_per_aweme?: number;
    concurrency?: number;
    request_delay_level?: DouyinRequestDelayLevel;
    request_interval_seconds?: number;
    account_id?: (string | null);
};

export type DouyinAwemeCreatorCrawlRequest = {
    browser_mode?: (DouyinBrowserMode | null);
    cookies?: (string | null);
    max_awemes?: number;
    fetch_comments?: boolean;
    fetch_sub_comments?: boolean;
    max_comments_per_aweme?: number;
    concurrency?: number;
    request_delay_level?: DouyinRequestDelayLevel;
    request_interval_seconds?: number;
    account_id?: (string | null);
};

export type DouyinAwemePublic = {
    id: string;
    task_id: string;
    aweme_id: string;
    aweme_type: string;
    title: string;
    description: string;
    create_time: (number | null);
    creator_hash: string;
    sec_uid: string;
    nickname: string;
    liked_count: number;
    collected_count: number;
    comment_count: number;
    share_count: number;
    aweme_url: string;
    cover_url: string;
    video_download_url: string;
    music_download_url: string;
    note_download_url: string;
    source_keyword: string;
    fetched_at: string;
};

export type DouyinAwemesPublic = {
    data: Array<DouyinAwemePublic>;
    count: number;
};

export type DouyinBrowserMode = 'local' | 'remote';

export type DouyinBrowserSlotPublic = {
    name: (string | null);
    label: string;
    is_default: boolean;
    available: boolean;
    configured: boolean;
    viewer_available: boolean;
    viewer_url: (string | null);
    cdp_healthy: boolean;
    page_count: number;
    active_page_title: (string | null);
    active_page_url: (string | null);
    latency_ms: (number | null);
    checked_at: string;
    occupied_account_id: (string | null);
    occupied_account_name: (string | null);
};

export type DouyinBrowserSlotsPublic = {
    data: Array<DouyinBrowserSlotPublic>;
    count: number;
};

export type DouyinBulkDeleteRequest = {
    ids: Array<(string)>;
};

export type DouyinCommentExportRequest = {
    aweme_ids: Array<(string)>;
};

export type DouyinCommentLibraryItemPublic = {
    comment: DouyinCommentPublic;
    aweme: DouyinAwemePublic;
    task_status: CrawlTaskStatus;
    task_created_at: string;
};

export type DouyinCommentLibraryPublic = {
    data: Array<DouyinCommentLibraryItemPublic>;
    count: number;
    summary: DouyinCommentLibrarySummaryPublic;
};

export type DouyinCommentLibrarySummaryPublic = {
    matched_count: number;
    top_level_count: number;
    reply_count: number;
    picture_count: number;
    total_like_count: number;
};

export type DouyinCommentPublic = {
    id: string;
    task_id: string;
    comment_id: string;
    aweme_id: string;
    parent_comment_id: string;
    content: string;
    create_time: (number | null);
    creator_hash: string;
    sec_uid: string;
    nickname: string;
    sub_comment_count: number;
    like_count: number;
    pictures: string;
    fetched_at: string;
};

export type DouyinCommentSelectionExportRequest = {
    comment_ids: Array<(string)>;
};

export type DouyinCommentsPublic = {
    data: Array<DouyinCommentPublic>;
    count: number;
};

export type DouyinCrawlType = 'search' | 'detail' | 'creator' | 'creator_from_aweme' | 'liked' | 'collected';

export type DouyinCreatorOptionPublic = {
    creator_hash: string;
    nickname: string;
    work_count: number;
};

export type DouyinCreatorOptionsPublic = {
    data: Array<DouyinCreatorOptionPublic>;
    count: number;
};

export type DouyinInteractionCreate = {
    task_id: string;
    aweme_id: string;
    account_id: string;
    interaction_type: DouyinInteractionType;
    target_comment_id?: (string | null);
    content: string;
};

export type DouyinInteractionDetailPublic = {
    id: string;
    task_id: string;
    account_id: (string | null);
    account_name: string;
    aweme_id: string;
    target_video_url: string;
    target_comment_id: (string | null);
    target_comment_content: (string | null);
    interaction_type: DouyinInteractionType;
    content_preview: string;
    status: DouyinInteractionStatus;
    failure_code: (string | null);
    error: (string | null);
    attempt_count: number;
    result_platform_id: (string | null);
    human_confirmed_at: (string | null);
    started_at: (string | null);
    finished_at: (string | null);
    created_at: string;
    updated_at: string;
    can_confirm: boolean;
    can_retry: boolean;
    can_cancel: boolean;
    content: string;
    events: Array<DouyinInteractionEventPublic>;
};

export type DouyinInteractionEventPublic = {
    id: string;
    event: string;
    from_status: (DouyinInteractionStatus | null);
    to_status: DouyinInteractionStatus;
    detail: (string | null);
    attempt_number: number;
    has_screenshot: boolean;
    created_at: string;
};

export type DouyinInteractionPreflightPublic = {
    allowed: boolean;
    failure_code?: (string | null);
    message: string;
    account_name: string;
    remaining_daily_quota: number;
    cooldown_until?: (string | null);
    duplicate_interaction_id?: (string | null);
};

export type DouyinInteractionPublic = {
    id: string;
    task_id: string;
    account_id: (string | null);
    account_name: string;
    aweme_id: string;
    target_video_url: string;
    target_comment_id: (string | null);
    target_comment_content: (string | null);
    interaction_type: DouyinInteractionType;
    content_preview: string;
    status: DouyinInteractionStatus;
    failure_code: (string | null);
    error: (string | null);
    attempt_count: number;
    result_platform_id: (string | null);
    human_confirmed_at: (string | null);
    started_at: (string | null);
    finished_at: (string | null);
    created_at: string;
    updated_at: string;
    can_confirm: boolean;
    can_retry: boolean;
    can_cancel: boolean;
};

export type DouyinInteractionQuotaPublic = {
    account_id: string;
    account_name: string;
    daily_limit: number;
    used_today: number;
    remaining_today: number;
    min_interval_seconds: number;
    cooldown_until: (string | null);
    available: boolean;
};

export type DouyinInteractionRetryRequest = {
    confirm_not_sent?: boolean;
};

export type DouyinInteractionsPublic = {
    data: Array<DouyinInteractionPublic>;
    count: number;
};

export type DouyinInteractionStatus = 'pending_confirmation' | 'queued' | 'running' | 'succeeded' | 'failed' | 'blocked' | 'needs_review' | 'cancelled';

export type DouyinInteractionType = 'video_comment' | 'comment_reply' | 'creator_message';

export type DouyinKeywordBatchMode = 'combined' | 'separate';

export type DouyinKeywordBatchTaskRequest = {
    keyword_ids: Array<(string)>;
    mode?: DouyinKeywordBatchMode;
    login_type?: DouyinLoginType;
    browser_mode?: (DouyinBrowserMode | null);
    start_page?: number;
    max_awemes?: number;
    fetch_comments?: boolean;
    fetch_sub_comments?: boolean;
    max_comments_per_aweme?: number;
    concurrency?: number;
    request_delay_level?: DouyinRequestDelayLevel;
    request_interval_seconds?: number;
    publish_time?: number;
    media_processing_mode?: MediaProcessingMode;
    media_storage?: (MediaStorageBackend | null);
    download_media?: boolean;
    translate_subtitles?: boolean;
    transcription_language?: string;
    account_id?: (string | null);
    account_pool_id?: (string | null);
    account_strategy?: DouyinAccountPoolStrategy;
};

export type DouyinKeywordBulkCreateRequest = {
    keywords: Array<(string)>;
    notes?: string;
    enabled?: boolean;
};

export type DouyinKeywordBulkCreateResult = {
    data: Array<DouyinKeywordPublic>;
    created_count: number;
    existing_count: number;
};

export type DouyinKeywordPublic = {
    id: string;
    keyword: string;
    enabled: boolean;
    notes: string;
    status: DouyinKeywordStatus;
    task_count: number;
    active_task_count: number;
    success_task_count: number;
    failed_task_count: number;
    aweme_count: number;
    last_task_id: (string | null);
    last_task_status: (CrawlTaskStatus | null);
    last_crawled_at: (string | null);
    created_at: string;
    updated_at: string;
};

export type DouyinKeywordsPublic = {
    data: Array<DouyinKeywordPublic>;
    count: number;
};

export type DouyinKeywordStatus = 'unprocessed' | 'active' | 'crawled' | 'failed';

export type DouyinKeywordSyncResult = {
    task_count: number;
    keyword_count: number;
    created_count: number;
    binding_count: number;
};

export type DouyinKeywordTaskBatchResult = {
    data: Array<CrawlTaskPublic>;
    count: number;
};

export type DouyinKeywordUpdate = {
    keyword?: (string | null);
    enabled?: (boolean | null);
    notes?: (string | null);
};

export type DouyinLibraryMediaMigrationRequest = {
    search?: (string | null);
    task_id?: (string | null);
    creator_hash?: (string | null);
    tag_id?: (string | null);
    subtitle_status?: 'all' | 'pending' | 'running' | 'completed' | 'failed';
};

export type subtitle_status = 'all' | 'pending' | 'running' | 'completed' | 'failed';

export type DouyinLoginType = 'qrcode' | 'cookie';

export type DouyinMediaAssetPublic = {
    id: string;
    task_id: string;
    aweme_id: string;
    storage_backend: MediaStorageBackend;
    status: MediaDownloadStatus;
    progress: number;
    attempt_count: number;
    mime_type: string;
    file_size: number;
    sha256: string;
    error: (string | null);
    download_available: boolean;
    created_at: string;
    updated_at: string;
    completed_at: (string | null);
    migration_status: MediaMigrationStatus;
    migration_progress: number;
    migration_attempt_count: number;
    migration_error: (string | null);
    migration_started_at: (string | null);
    migration_finished_at: (string | null);
    subtitle: (DouyinSubtitlePublic | null);
};

export type DouyinMediaAssetsPublic = {
    data: Array<DouyinMediaAssetPublic>;
    count: number;
};

export type DouyinMediaMigrationAccepted = {
    queued: number;
    skipped: number;
    message: string;
};

export type DouyinMediaMigrationRequest = {
    asset_ids?: Array<(string)>;
};

export type DouyinMediaProcessRequest = {
    media_storage?: (MediaStorageBackend | null);
    translate_subtitles?: boolean;
    force_retranslate?: boolean;
    transcription_language?: string;
    cookies?: (string | null);
};

export type DouyinMediaRetryRequest = {
    asset_ids?: Array<(string)>;
    retry_downloads?: boolean;
    retry_subtitles?: boolean;
    force_retranslate?: boolean;
};

export type DouyinMediaSummaryPublic = {
    total: number;
    queued: number;
    downloading: number;
    downloaded: number;
    download_failed: number;
    subtitle_pending: number;
    subtitle_running: number;
    subtitle_completed: number;
    subtitle_failed: number;
    local_downloaded: number;
    minio_downloaded: number;
    migration_queued: number;
    migration_running: number;
    migration_cleanup_pending: number;
    migration_completed: number;
    migration_failed: number;
};

export type DouyinRequestDelayLevel = 'fast' | 'steady' | 'ultra_steady';

export type DouyinSubtitleExportFormat = 'txt' | 'srt' | 'vtt';

export type DouyinSubtitleExportRequest = {
    aweme_ids: Array<(string)>;
    format?: DouyinSubtitleExportFormat;
};

export type DouyinSubtitlePublic = {
    id: string;
    asset_id: string;
    task_id: string;
    aweme_id: string;
    status: SubtitleStatus;
    progress: number;
    attempt_count: number;
    requested_backend: string;
    actual_backend: string;
    model: string;
    language: string;
    duration_seconds: number;
    full_text: string;
    segments: Array<{
        [key: string]: unknown;
    }>;
    error: (string | null);
    created_at: string;
    started_at: (string | null);
    finished_at: (string | null);
};

export type DouyinTagPublic = {
    id: string;
    name: string;
    aweme_count: number;
    task_count: number;
    last_seen_at: string;
    created_at: string;
};

export type DouyinTagRefPublic = {
    id: string;
    name: string;
};

export type DouyinTagsPublic = {
    data: Array<DouyinTagPublic>;
    count: number;
};

export type DouyinTagSyncResult = {
    aweme_count: number;
    tag_count: number;
    created_count: number;
    binding_count: number;
};

export type DouyinTrackCreate = {
    name: string;
    description?: string;
    prompt?: string;
    keywords?: Array<(string)>;
};

export type DouyinTrackDetailPublic = {
    id: string;
    name: string;
    description: string;
    enabled: boolean;
    keyword_count: number;
    enabled_keyword_count: number;
    task_count: number;
    active_task_count: number;
    aweme_count: number;
    comment_count: number;
    last_task_id: (string | null);
    last_task_status: (CrawlTaskStatus | null);
    last_run_at: (string | null);
    created_at: string;
    updated_at: string;
    prompt: string;
};

export type DouyinTrackKeywordAdd = {
    keywords: Array<(string)>;
};

export type DouyinTrackPublic = {
    id: string;
    name: string;
    description: string;
    enabled: boolean;
    keyword_count: number;
    enabled_keyword_count: number;
    task_count: number;
    active_task_count: number;
    aweme_count: number;
    comment_count: number;
    last_task_id: (string | null);
    last_task_status: (CrawlTaskStatus | null);
    last_run_at: (string | null);
    created_at: string;
    updated_at: string;
};

export type DouyinTracksPublic = {
    data: Array<DouyinTrackPublic>;
    count: number;
};

export type DouyinTrackTaskRequest = {
    keyword_ids?: Array<(string)>;
    mode?: DouyinKeywordBatchMode;
    max_awemes?: number;
    fetch_comments?: boolean;
    fetch_sub_comments?: boolean;
    max_comments_per_aweme?: number;
    request_delay_level?: DouyinRequestDelayLevel;
    publish_time?: number;
    download_media?: boolean;
    translate_subtitles?: boolean;
    account_id?: (string | null);
    account_pool_id?: (string | null);
    account_strategy?: DouyinAccountPoolStrategy;
};

export type DouyinTrackUpdate = {
    name?: (string | null);
    description?: (string | null);
    prompt?: (string | null);
    enabled?: (boolean | null);
};

export type DouyinUserActionPublic = {
    id: string;
    task_id: string;
    account_hash: string;
    aweme_id: string;
    action_type: string;
    observed_at: string;
};

export type DouyinUserActionsPublic = {
    data: Array<DouyinUserActionPublic>;
    count: number;
};

export type DouyinWorkPublic = {
    aweme: DouyinAwemePublic;
    persisted_comment_count: number;
    media: (DouyinMediaAssetPublic | null);
    tags?: Array<DouyinTagRefPublic>;
};

export type DouyinWorksPublic = {
    data: Array<DouyinWorkPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IntegrationDocsPublic = {
    api_title: string;
    api_version: string;
    api_openapi_url: string;
    api_swagger_url: string;
    api_operations: Array<ApiOperationDocPublic>;
    api_operation_count: number;
    mcp_server_name: string;
    mcp_streamable_http_url: string;
    mcp_health_url: string;
    mcp_stdio_command: string;
    mcp_http_command: string;
    mcp_tools: Array<McpToolDocPublic>;
    mcp_tool_count: number;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type McpToolDocPublic = {
    name: string;
    title: (string | null);
    description: string;
    input_schema: {
        [key: string]: unknown;
    };
    output_schema: ({
    [key: string]: unknown;
} | null);
};

export type MediaDownloadStatus = 'queued' | 'downloading' | 'downloaded' | 'failed';

export type MediaMigrationStatus = 'idle' | 'queued' | 'uploading' | 'verifying' | 'switching' | 'cleanup_pending' | 'completed' | 'failed';

export type MediaProcessingMode = 'none' | 'immediate' | 'batch';

export type MediaStorageBackend = 'local' | 'minio';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SubtitleStatus = 'pending' | 'running' | 'completed' | 'failed';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DouyinCreateTaskData = {
    requestBody: CrawlTaskCreate;
};

export type DouyinCreateTaskResponse = (CrawlTaskPublic);

export type DouyinListTasksData = {
    limit?: number;
    skip?: number;
};

export type DouyinListTasksResponse = (CrawlTasksPublic);

export type DouyinListCommentLibraryData = {
    awemeId?: (string | null);
    commentContent?: (string | null);
    commentType?: 'all' | 'top_level' | 'reply';
    hasPictures?: 'all' | 'yes' | 'no';
    limit?: number;
    maxLikes?: (number | null);
    minLikes?: (number | null);
    publishedFrom?: (number | null);
    publishedTo?: (number | null);
    search?: (string | null);
    skip?: number;
    sortBy?: 'published_at' | 'like_count' | 'sub_comment_count' | 'fetched_at';
    sortOrder?: 'asc' | 'desc';
    sourceKeyword?: (string | null);
    taskId?: (string | null);
    videoCreator?: (string | null);
};

export type DouyinListCommentLibraryResponse = (DouyinCommentLibraryPublic);

export type DouyinExportCommentSelectionData = {
    requestBody: DouyinCommentSelectionExportRequest;
};

export type DouyinExportCommentSelectionResponse = (unknown);

export type DouyinListLibraryCreatorsData = {
    taskId?: (string | null);
};

export type DouyinListLibraryCreatorsResponse = (DouyinCreatorOptionsPublic);

export type DouyinListLibraryWorksData = {
    creatorHash?: (string | null);
    downloadStatus?: 'all' | 'queued' | 'downloading' | 'downloaded' | 'failed';
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: 'published_at' | 'liked_count' | 'comment_count' | 'collected_count' | 'persisted_comment_count' | 'downloaded_at' | 'file_size' | 'fetched_at';
    sortOrder?: 'asc' | 'desc';
    storageBackend?: 'all' | 'local' | 'minio';
    subtitleStatus?: 'all' | 'pending' | 'running' | 'completed' | 'failed';
    tagId?: (string | null);
    taskId?: (string | null);
};

export type DouyinListLibraryWorksResponse = (DouyinWorksPublic);

export type DouyinMigrateLibraryMediaToMinioData = {
    requestBody: DouyinLibraryMediaMigrationRequest;
};

export type DouyinMigrateLibraryMediaToMinioResponse = (DouyinMediaMigrationAccepted);

export type DouyinGetTaskData = {
    taskId: string;
};

export type DouyinGetTaskResponse = (CrawlTaskPublic);

export type DouyinListTaskShardsData = {
    taskId: string;
};

export type DouyinListTaskShardsResponse = (CrawlTaskShardsPublic);

export type DouyinCancelTaskData = {
    taskId: string;
};

export type DouyinCancelTaskResponse = (Message);

export type DouyinResumeTaskData = {
    requestBody: CrawlTaskResumeRequest;
    taskId: string;
};

export type DouyinResumeTaskResponse = (CrawlTaskPublic);

export type DouyinListMediaData = {
    limit?: number;
    skip?: number;
    taskId: string;
};

export type DouyinListMediaResponse = (DouyinMediaAssetsPublic);

export type DouyinGetMediaSummaryData = {
    taskId: string;
};

export type DouyinGetMediaSummaryResponse = (DouyinMediaSummaryPublic);

export type DouyinMigrateMediaToMinioData = {
    requestBody: DouyinMediaMigrationRequest;
    taskId: string;
};

export type DouyinMigrateMediaToMinioResponse = (DouyinMediaMigrationAccepted);

export type DouyinProcessMediaData = {
    requestBody: DouyinMediaProcessRequest;
    taskId: string;
};

export type DouyinProcessMediaResponse = (CrawlTaskPublic);

export type DouyinRetryMediaData = {
    requestBody: DouyinMediaRetryRequest;
    taskId: string;
};

export type DouyinRetryMediaResponse = (Message);

export type DouyinRetranslateMediaData = {
    assetId: string;
    taskId: string;
};

export type DouyinRetranslateMediaResponse = (Message);

export type DouyinDownloadMediaFileData = {
    assetId: string;
    taskId: string;
};

export type DouyinDownloadMediaFileResponse = (unknown);

export type DouyinCreateMediaPreviewSessionData = {
    assetId: string;
    taskId: string;
};

export type DouyinCreateMediaPreviewSessionResponse = (Message);

export type DouyinPreviewMediaFileData = {
    assetId: string;
    douyinMediaPreview?: (string | null);
    range?: (string | null);
    taskId: string;
};

export type DouyinPreviewMediaFileResponse = (unknown);

export type DouyinGetQrcodeData = {
    taskId: string;
};

export type DouyinGetQrcodeResponse = (unknown);

export type DouyinListWorksData = {
    downloadStatus?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: 'published_at' | 'liked_count' | 'comment_count' | 'collected_count' | 'persisted_comment_count' | 'fetched_at';
    sortOrder?: 'asc' | 'desc';
    storageBackend?: (string | null);
    subtitleStatus?: (string | null);
    tagId?: (string | null);
    taskId: string;
};

export type DouyinListWorksResponse = (DouyinWorksPublic);

export type DouyinGetWorkData = {
    awemeId: string;
    taskId: string;
};

export type DouyinGetWorkResponse = (DouyinWorkPublic);

export type DouyinListAwemesData = {
    limit?: number;
    skip?: number;
    sortBy?: 'published_at' | 'liked_count' | 'comment_count' | 'collected_count' | 'fetched_at';
    sortOrder?: 'asc' | 'desc';
    taskId: string;
};

export type DouyinListAwemesResponse = (DouyinAwemesPublic);

export type DouyinRecrawlAwemeCommentsData = {
    awemeId: string;
    requestBody: DouyinAwemeCommentCrawlRequest;
    taskId: string;
};

export type DouyinRecrawlAwemeCommentsResponse = (CrawlTaskPublic);

export type DouyinCrawlAwemeCreatorData = {
    awemeId: string;
    requestBody: DouyinAwemeCreatorCrawlRequest;
    taskId: string;
};

export type DouyinCrawlAwemeCreatorResponse = (CrawlTaskPublic);

export type DouyinListCommentsData = {
    awemeId?: (string | null);
    limit?: number;
    skip?: number;
    sortBy?: 'published_at' | 'like_count' | 'fetched_at';
    sortOrder?: 'asc' | 'desc';
    taskId: string;
};

export type DouyinListCommentsResponse = (DouyinCommentsPublic);

export type DouyinExportCommentsData = {
    requestBody: DouyinCommentExportRequest;
    taskId: string;
};

export type DouyinExportCommentsResponse = (unknown);

export type DouyinExportSubtitlesData = {
    requestBody: DouyinSubtitleExportRequest;
    taskId: string;
};

export type DouyinExportSubtitlesResponse = (unknown);

export type DouyinListActionsData = {
    limit?: number;
    skip?: number;
    taskId: string;
};

export type DouyinListActionsResponse = (DouyinUserActionsPublic);

export type DouyinAccountsListAccountsData = {
    limit?: number;
    skip?: number;
};

export type DouyinAccountsListAccountsResponse = (DouyinAccountsPublic);

export type DouyinAccountsAddAccountData = {
    requestBody: DouyinAccountCreate;
};

export type DouyinAccountsAddAccountResponse = (DouyinAccountPublic);

export type DouyinAccountsListBrowserSlotsResponse = (DouyinBrowserSlotsPublic);

export type DouyinAccountsEditAccountData = {
    accountId: string;
    requestBody: DouyinAccountUpdate;
};

export type DouyinAccountsEditAccountResponse = (DouyinAccountPublic);

export type DouyinAccountsDeleteAccountData = {
    accountId: string;
};

export type DouyinAccountsDeleteAccountResponse = (Message);

export type DouyinAccountsStartAccountLoginData = {
    accountId: string;
};

export type DouyinAccountsStartAccountLoginResponse = (DouyinAccountLoginSessionPublic);

export type DouyinAccountsVerifyAccountLoginData = {
    accountId: string;
};

export type DouyinAccountsVerifyAccountLoginResponse = (DouyinAccountPublic);

export type DouyinAccountsListPoolsResponse = (DouyinAccountPoolsPublic);

export type DouyinAccountsAddPoolData = {
    requestBody: DouyinAccountPoolCreate;
};

export type DouyinAccountsAddPoolResponse = (DouyinAccountPoolPublic);

export type DouyinAccountsEditPoolData = {
    poolId: string;
    requestBody: DouyinAccountPoolUpdate;
};

export type DouyinAccountsEditPoolResponse = (DouyinAccountPoolPublic);

export type DouyinAccountsDeletePoolData = {
    poolId: string;
};

export type DouyinAccountsDeletePoolResponse = (Message);

export type DouyinInteractionsPreflightInteractionData = {
    requestBody: DouyinInteractionCreate;
};

export type DouyinInteractionsPreflightInteractionResponse = (DouyinInteractionPreflightPublic);

export type DouyinInteractionsPrepareInteractionData = {
    requestBody: DouyinInteractionCreate;
};

export type DouyinInteractionsPrepareInteractionResponse = (DouyinInteractionPublic);

export type DouyinInteractionsListInteractionsData = {
    awemeId?: (string | null);
    interactionType?: (DouyinInteractionType | null);
    limit?: number;
    skip?: number;
    status?: (DouyinInteractionStatus | null);
    taskId?: (string | null);
};

export type DouyinInteractionsListInteractionsResponse = (DouyinInteractionsPublic);

export type DouyinInteractionsListInteractionQuotaResponse = (Array<DouyinInteractionQuotaPublic>);

export type DouyinInteractionsGetInteractionData = {
    interactionId: string;
};

export type DouyinInteractionsGetInteractionResponse = (DouyinInteractionDetailPublic);

export type DouyinInteractionsGetInteractionEventScreenshotData = {
    eventId: string;
    interactionId: string;
};

export type DouyinInteractionsGetInteractionEventScreenshotResponse = (unknown);

export type DouyinInteractionsConfirmInteractionData = {
    interactionId: string;
};

export type DouyinInteractionsConfirmInteractionResponse = (DouyinInteractionPublic);

export type DouyinInteractionsRetryInteractionData = {
    interactionId: string;
    requestBody: DouyinInteractionRetryRequest;
};

export type DouyinInteractionsRetryInteractionResponse = (DouyinInteractionPublic);

export type DouyinInteractionsCancelInteractionData = {
    interactionId: string;
};

export type DouyinInteractionsCancelInteractionResponse = (DouyinInteractionPublic);

export type DouyinKeywordsListKeywordsData = {
    enabled?: (boolean | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: 'keyword' | 'status' | 'task_count' | 'aweme_count' | 'last_crawled_at' | 'created_at';
    sortOrder?: 'asc' | 'desc';
    status?: (DouyinKeywordStatus | null);
};

export type DouyinKeywordsListKeywordsResponse = (DouyinKeywordsPublic);

export type DouyinKeywordsBulkCreateKeywordsData = {
    requestBody: DouyinKeywordBulkCreateRequest;
};

export type DouyinKeywordsBulkCreateKeywordsResponse = (DouyinKeywordBulkCreateResult);

export type DouyinKeywordsEditKeywordData = {
    keywordId: string;
    requestBody: DouyinKeywordUpdate;
};

export type DouyinKeywordsEditKeywordResponse = (DouyinKeywordPublic);

export type DouyinKeywordsDeleteKeywordData = {
    keywordId: string;
};

export type DouyinKeywordsDeleteKeywordResponse = (Message);

export type DouyinKeywordsBulkDeleteKeywordsData = {
    requestBody: DouyinBulkDeleteRequest;
};

export type DouyinKeywordsBulkDeleteKeywordsResponse = (Message);

export type DouyinKeywordsListKeywordTasksData = {
    keywordId: string;
};

export type DouyinKeywordsListKeywordTasksResponse = (Array<CrawlTaskPublic>);

export type DouyinKeywordsSyncKeywordsFromTaskData = {
    taskId: string;
};

export type DouyinKeywordsSyncKeywordsFromTaskResponse = (DouyinKeywordSyncResult);

export type DouyinKeywordsSyncHistoricalKeywordsResponse = (DouyinKeywordSyncResult);

export type DouyinKeywordsCreateKeywordTasksData = {
    requestBody: DouyinKeywordBatchTaskRequest;
};

export type DouyinKeywordsCreateKeywordTasksResponse = (DouyinKeywordTaskBatchResult);

export type DouyinTagsListTagsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: 'name' | 'aweme_count' | 'task_count' | 'last_seen_at';
    sortOrder?: 'asc' | 'desc';
    taskId?: (string | null);
};

export type DouyinTagsListTagsResponse = (DouyinTagsPublic);

export type DouyinTagsSyncTagsResponse = (DouyinTagSyncResult);

export type DouyinTracksListTracksData = {
    enabled?: (boolean | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type DouyinTracksListTracksResponse = (DouyinTracksPublic);

export type DouyinTracksAddTrackData = {
    requestBody: DouyinTrackCreate;
};

export type DouyinTracksAddTrackResponse = (DouyinTrackDetailPublic);

export type DouyinTracksGetTrackData = {
    trackId: string;
};

export type DouyinTracksGetTrackResponse = (DouyinTrackDetailPublic);

export type DouyinTracksEditTrackData = {
    requestBody: DouyinTrackUpdate;
    trackId: string;
};

export type DouyinTracksEditTrackResponse = (DouyinTrackDetailPublic);

export type DouyinTracksDeleteTrackData = {
    trackId: string;
};

export type DouyinTracksDeleteTrackResponse = (Message);

export type DouyinTracksBulkDeleteTracksData = {
    requestBody: DouyinBulkDeleteRequest;
};

export type DouyinTracksBulkDeleteTracksResponse = (Message);

export type DouyinTracksListTrackKeywordsData = {
    trackId: string;
};

export type DouyinTracksListTrackKeywordsResponse = (DouyinKeywordsPublic);

export type DouyinTracksAppendTrackKeywordsData = {
    requestBody: DouyinTrackKeywordAdd;
    trackId: string;
};

export type DouyinTracksAppendTrackKeywordsResponse = (DouyinKeywordsPublic);

export type DouyinTracksRemoveTrackKeywordData = {
    keywordId: string;
    trackId: string;
};

export type DouyinTracksRemoveTrackKeywordResponse = (Message);

export type DouyinTracksCreateTrackTasksData = {
    requestBody: DouyinTrackTaskRequest;
    trackId: string;
};

export type DouyinTracksCreateTrackTasksResponse = (DouyinKeywordTaskBatchResult);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SystemIntegrationsGetIntegrationDocsResponse = (IntegrationDocsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);
