/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutDouyinLibraryRouteImport } from './routes/_layout/douyin-library'
import { Route as LayoutDouyinKeywordsRouteImport } from './routes/_layout/douyin-keywords'
import { Route as LayoutDouyinAccountsRouteImport } from './routes/_layout/douyin-accounts'
import { Route as LayoutDouyinRouteImport } from './routes/_layout/douyin'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutDouyinTaskIdRouteImport } from './routes/_layout/douyin_.$taskId'
import { Route as LayoutDouyinTaskIdFeedRouteImport } from './routes/_layout/douyin_.$taskId.feed'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDouyinLibraryRoute = LayoutDouyinLibraryRouteImport.update({
  id: '/douyin-library',
  path: '/douyin-library',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDouyinKeywordsRoute = LayoutDouyinKeywordsRouteImport.update({
  id: '/douyin-keywords',
  path: '/douyin-keywords',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDouyinAccountsRoute = LayoutDouyinAccountsRouteImport.update({
  id: '/douyin-accounts',
  path: '/douyin-accounts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDouyinRoute = LayoutDouyinRouteImport.update({
  id: '/douyin',
  path: '/douyin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDouyinTaskIdRoute = LayoutDouyinTaskIdRouteImport.update({
  id: '/douyin_/$taskId',
  path: '/douyin/$taskId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDouyinTaskIdFeedRoute = LayoutDouyinTaskIdFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => LayoutDouyinTaskIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/douyin': typeof LayoutDouyinRoute
  '/douyin-accounts': typeof LayoutDouyinAccountsRoute
  '/douyin-keywords': typeof LayoutDouyinKeywordsRoute
  '/douyin-library': typeof LayoutDouyinLibraryRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/douyin/$taskId': typeof LayoutDouyinTaskIdRouteWithChildren
  '/douyin/$taskId/feed': typeof LayoutDouyinTaskIdFeedRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/douyin': typeof LayoutDouyinRoute
  '/douyin-accounts': typeof LayoutDouyinAccountsRoute
  '/douyin-keywords': typeof LayoutDouyinKeywordsRoute
  '/douyin-library': typeof LayoutDouyinLibraryRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/douyin/$taskId': typeof LayoutDouyinTaskIdRouteWithChildren
  '/douyin/$taskId/feed': typeof LayoutDouyinTaskIdFeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/douyin': typeof LayoutDouyinRoute
  '/_layout/douyin-accounts': typeof LayoutDouyinAccountsRoute
  '/_layout/douyin-keywords': typeof LayoutDouyinKeywordsRoute
  '/_layout/douyin-library': typeof LayoutDouyinLibraryRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/douyin_/$taskId': typeof LayoutDouyinTaskIdRouteWithChildren
  '/_layout/douyin_/$taskId/feed': typeof LayoutDouyinTaskIdFeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/douyin'
    | '/douyin-accounts'
    | '/douyin-keywords'
    | '/douyin-library'
    | '/items'
    | '/settings'
    | '/douyin/$taskId'
    | '/douyin/$taskId/feed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/douyin'
    | '/douyin-accounts'
    | '/douyin-keywords'
    | '/douyin-library'
    | '/items'
    | '/settings'
    | '/'
    | '/douyin/$taskId'
    | '/douyin/$taskId/feed'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/douyin'
    | '/_layout/douyin-accounts'
    | '/_layout/douyin-keywords'
    | '/_layout/douyin-library'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/douyin_/$taskId'
    | '/_layout/douyin_/$taskId/feed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/douyin-library': {
      id: '/_layout/douyin-library'
      path: '/douyin-library'
      fullPath: '/douyin-library'
      preLoaderRoute: typeof LayoutDouyinLibraryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/douyin-keywords': {
      id: '/_layout/douyin-keywords'
      path: '/douyin-keywords'
      fullPath: '/douyin-keywords'
      preLoaderRoute: typeof LayoutDouyinKeywordsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/douyin-accounts': {
      id: '/_layout/douyin-accounts'
      path: '/douyin-accounts'
      fullPath: '/douyin-accounts'
      preLoaderRoute: typeof LayoutDouyinAccountsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/douyin': {
      id: '/_layout/douyin'
      path: '/douyin'
      fullPath: '/douyin'
      preLoaderRoute: typeof LayoutDouyinRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/douyin_/$taskId': {
      id: '/_layout/douyin_/$taskId'
      path: '/douyin/$taskId'
      fullPath: '/douyin/$taskId'
      preLoaderRoute: typeof LayoutDouyinTaskIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/douyin_/$taskId/feed': {
      id: '/_layout/douyin_/$taskId/feed'
      path: '/feed'
      fullPath: '/douyin/$taskId/feed'
      preLoaderRoute: typeof LayoutDouyinTaskIdFeedRouteImport
      parentRoute: typeof LayoutDouyinTaskIdRoute
    }
  }
}

interface LayoutDouyinTaskIdRouteChildren {
  LayoutDouyinTaskIdFeedRoute: typeof LayoutDouyinTaskIdFeedRoute
}

const LayoutDouyinTaskIdRouteChildren: LayoutDouyinTaskIdRouteChildren = {
  LayoutDouyinTaskIdFeedRoute: LayoutDouyinTaskIdFeedRoute,
}

const LayoutDouyinTaskIdRouteWithChildren =
  LayoutDouyinTaskIdRoute._addFileChildren(LayoutDouyinTaskIdRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDouyinRoute: typeof LayoutDouyinRoute
  LayoutDouyinAccountsRoute: typeof LayoutDouyinAccountsRoute
  LayoutDouyinKeywordsRoute: typeof LayoutDouyinKeywordsRoute
  LayoutDouyinLibraryRoute: typeof LayoutDouyinLibraryRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDouyinTaskIdRoute: typeof LayoutDouyinTaskIdRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDouyinRoute: LayoutDouyinRoute,
  LayoutDouyinAccountsRoute: LayoutDouyinAccountsRoute,
  LayoutDouyinKeywordsRoute: LayoutDouyinKeywordsRoute,
  LayoutDouyinLibraryRoute: LayoutDouyinLibraryRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDouyinTaskIdRoute: LayoutDouyinTaskIdRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
